import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { failClosedClaudeOutput } from "./hooks";
import { AGENT_DENY } from "./steer";
import claudeCommandSettings from "../../../examples/claude-command-settings.json";
import claudeSettings from "../../../examples/claude-settings.json";
import cursorHooks from "../../../examples/cursor-hooks.json";
import codexHooks from "../../../examples/codex-hooks.json";
import grokHooks from "../../../examples/grok-hooks.json";
import piHooksSettings from "../../../examples/pi-hooks-settings.json";
import pluginHooks from "../../../hooks/hooks.json";

const root = join(dirname(fileURLToPath(import.meta.url)), "../../..");

function httpUrl(entry: {
  hooks?: { type?: string; url?: string; command?: string }[];
}): string | undefined {
  return entry.hooks?.find((hook) => hook.type === "http")?.url;
}

function commandOf(entry: {
  hooks?: { type?: string; url?: string; command?: string }[];
}): string | undefined {
  return entry.hooks?.find((hook) => hook.type === "command")?.command;
}

describe("hook pack stays aligned with examples/", () => {
  it("uses the same Claude HTTP sidecar URL as examples/claude-settings.json", () => {
    const examplePrompt = claudeSettings.hooks.UserPromptSubmit[0];
    const exampleStop = claudeSettings.hooks.Stop[0];
    const pluginPrompt = pluginHooks.hooks.UserPromptSubmit[0];
    const pluginStop = pluginHooks.hooks.Stop[0];
    expect(httpUrl(pluginPrompt)).toBe(httpUrl(examplePrompt));
    expect(httpUrl(pluginStop)).toBe(httpUrl(exampleStop));
    expect(httpUrl(pluginPrompt)).toBe(
      "http://127.0.0.1:43147/api/hooks/claude"
    );
  });

  it("keeps the same PreToolUse matcher as examples/claude-command-settings.json", () => {
    const example = claudeCommandSettings.hooks.PreToolUse[0];
    const plugin = pluginHooks.hooks.PreToolUse[0];
    expect(plugin.matcher).toBe(example.matcher);
    expect(example.matcher).toBe("Bash|Edit|Write|StrReplace");
    expect(commandOf(example)).toBe("npx tsx hooks/run.ts claude");
    expect(commandOf(plugin)).toContain("hooks/claude-hook.sh");
  });

  it("documents Cursor failClosed on mutating gates in examples/cursor-hooks.json", () => {
    const shell = cursorHooks.hooks.beforeShellExecution[0];
    const tool = cursorHooks.hooks.preToolUse[0];
    expect(shell.failClosed).toBe(true);
    expect(tool.failClosed).toBe(true);
    expect(shell.command).toBe("npx tsx hooks/run.ts cursor");
  });
});

describe("discoverability copy", () => {
  const PUBLIC_COPY_PATHS = [
    "README.md",
    "docs/hosts.md",
    "docs/install-plugin.md",
    "docs/shape.md",
    "docs/eval-integrity.md",
    "src/app/install/page.tsx",
    "src/app/literature/page.tsx",
    ".agents/skills/rh-guard/SKILL.md",
    ".agents/skills/rh-guard/references/gates.md",
  ] as const;

  const RESEARCH_OPS_CLUTTER =
    /research-prompt|Deep Research|ChatGPT Pro|Gemini Deep Research|Both copies are private|Suggested description|GitHub topics/i;

  it("keeps the public product README, not research-ops housekeeping", () => {
    const readme = readFileSync(join(root, "README.md"), "utf8");
    expect(readme).not.toMatch(/Both copies are private/i);
    expect(readme).not.toMatch(RESEARCH_OPS_CLUTTER);
    expect(readme).toMatch(/public on GitHub/i);
    expect(readme).toMatch(/^# Reward Hack Guard/m);
    expect(readme).toMatch(/RH Guard \(`rh-guard`\)/);
    expect(readme).not.toMatch(/Hack Radar/);
    expect(readme).toMatch(/24601\/Augustus/);
    expect(readme).toMatch(/examples\/claude-settings\.json/);
    expect(readme).toMatch(/examples\/cursor-hooks\.json/);
    expect(readme).toMatch(/docs\/hosts\.md/);
    expect(readme).toMatch(/Codex/);
    expect(readme).toMatch(/DeepSeek Harness/);
    expect(readme).toMatch(/hooks\/run\.ts dsh/);
    expect(readme).toMatch(/command-hook/);
    expect(readme).toMatch(/DSH \(generic\/adapter\)/);
    expect(readme).toMatch(/support via ToolRuntime wrap/i);
    expect(readme).toMatch(/no public Jev reward-hack ROC/i);
    expect(readme).toMatch(/Lexical \/ GLiClass fallback is \*\*degraded\*\*/);
    expect(readme).toMatch(/huntedman\/JevLint/);
    expect(readme).toMatch(/thevibeworks\/jevgate/);
    expect(readme).toMatch(/allowlist that proves what may run/i);
    expect(readme).toMatch(/write → check → fix/);
    expect(readme).toMatch(/fastino-ai\/GLiGuard/);
    expect(readme).toMatch(/encoder-based LLM prompt\/response safety guard/i);
    expect(readme).toMatch(/reward-hack \/ eval integrity gate/i);
    expect(readme).toMatch(/coldteadotai\/abide/);
    expect(readme).toMatch(/soft project instructions/i);
    expect(readme).toMatch(/banded confidence/);
    expect(readme).toMatch(/Abide does not catch reward hacking/);
    expect(readme).toMatch(/Eval integrity & measurement/);
    expect(readme).toMatch(/harbor-framework\/harbor/);
    expect(readme).toMatch(/dayhaysoos\/jevals/);
    expect(readme).toMatch(/memovai\/openevals/);
    expect(readme).toMatch(/cheap parallel/);
    expect(readme).toMatch(/caiovicentino\/jev-align/);
    expect(readme).toMatch(/AntonioCoppe\/jev-harness/);
    expect(readme).toMatch(/phin-tech\/pi-jev-approver/);
    expect(readme).toMatch(/commandRules/);
    expect(readme).toMatch(/ngallodev-software\/agent-workflow-typesafe-ai/);
    expect(readme).toMatch(/never changes host routing\/executor/);
    expect(readme).toMatch(/alexykn\/jevscan/);
    expect(readme).toMatch(/tree-sitter extract/);
    expect(readme).toMatch(/ufx7\/jev-testbench/);
    expect(readme).toMatch(/llm_autonomous/);
    expect(readme).toMatch(/scripted_plus_jev/);
    expect(readme).toMatch(/llm_plus_jev/);
    expect(readme).toMatch(/do not claim collab helps without arms/);
    expect(readme).toMatch(/CeamKrier\/semantic-firewall/);
    expect(readme).toMatch(/skip-when-absent/);
    expect(readme).toMatch(/hard envelope stays structural/);
    expect(readme).toMatch(/RahulBalakavi\/claude-code-jev/);
    expect(readme).toMatch(/230\.8ms p50/);
    expect(readme).toMatch(/263\.9ms mean/);
    expect(readme).toMatch(/mjyoke1111\/jev-agent-safety-arena/);
    expect(readme).toMatch(/Mandrilsquad1441\/jev-model-router/);
    expect(readme).toMatch(/not a rh-guard peer/);
    expect(readme).toMatch(/m-newhauser\/gliner25-compaction/);
    expect(readme).toMatch(/fastino\/gliner2\.5-base-v1/);
    expect(readme).toMatch(/character-offset/);
    expect(readme).toMatch(/keep_full/);
    expect(readme).toMatch(/shadowMode/);
    expect(readme).toMatch(/hard shell\/mutation policy overrides the soft model/);
    expect(readme).toMatch(/Not reward-hack detection/);
    expect(readme).toMatch(/fail-closed retention vs fail-open rest/);
    expect(readme).toMatch(/CaseReed\/latch/);
    expect(readme).toMatch(/Gate: PASS/);
    expect(readme).toMatch(/Gate: BLOCK/);
    expect(readme).toMatch(/ignore_as_infra/);
    expect(readme).toMatch(/VladyslavHontar\/clear-head/);
    expect(readme).toMatch(/CONTRADICTED/);
    expect(readme).toMatch(/LightningK0ala\/jev-marshal/);
    expect(readme).toMatch(/empty public tree at capture/);
    expect(readme).toMatch(/Victor-Casado\/if-ai/);
    expect(readme).toMatch(/shitianfang\/wakegate/);
    expect(readme).toMatch(/fail-open wake gate/);
    expect(readme).toMatch(/alexsatch\/omp-auto-mode/);
    expect(readme).toMatch(/fdemir\/toolgate/);
    expect(readme).toMatch(/ndolinschi\/toolgate/);
    expect(readme).toMatch(/`allow` \/ `block` \/ `review`/);
    expect(readme).toMatch(/given → expected → actual/);
    expect(readme).toMatch(/egma-ai\/jev-reviewer/);
    expect(readme).toMatch(/attention priorities/);
    expect(readme).toMatch(/blocked as unsafe/);
    expect(readme).toMatch(/EpicEric\/safe-sh/);
    expect(readme).toMatch(/static shell/);
    expect(readme).toMatch(/somoore\/interlock/);
    expect(readme).toMatch(/secrets never enter the agent/);
    expect(readme).toMatch(/38-case/);
    expect(readme).toMatch(/not a blind paper/);
    expect(readme).toMatch(/epiphany-dynamics\/port-cleanup/);
    expect(readme).toMatch(/identity re-check before SIGTERM/);
    expect(readme).toMatch(/app-owned explanation text/);
    expect(readme).toMatch(/manikanda-kumar\/jev-dspy-control-plane/);
    expect(readme).toMatch(/cannot add routes or tools/);
    expect(readme).toMatch(/meetr1912\/jev-arena/);
    expect(readme).toMatch(/overconfident in the low bins/);
    expect(readme).toMatch(/mja00\/cmdc-auto-mode/);
    expect(readme).toMatch(/beforeToolCall/);
    expect(readme).toMatch(/within_scope ≤ 0\.25/);
    expect(readme).toMatch(/auto-fail-closed/);
    expect(readme).toMatch(/ragelink\/firehose-judge/);
    expect(readme).toMatch(/needs a human/);
    expect(readme).toMatch(/skiingfalcon\/jav-email-cascade/);
    expect(readme).toMatch(/decide → policy → LLM leftover/);
    expect(readme).toMatch(/injection_suspected/);
    expect(readme).toMatch(/cannot tell/);
    expect(readme).toMatch(/never rounded/);
    expect(readme).toMatch(/mossburgh\/waymode/);
    expect(readme).toMatch(/typed actions/);
    expect(readme).toMatch(/retained evidence/);
    expect(readme).toMatch(/Jev confidence grants no permission/);
    expect(readme).toMatch(/adamjralph\/skill-broker/);
    expect(readme).toMatch(/never grants access/);
    expect(readme).toMatch(/luw2007\/omp-jev-extensions/);
    expect(readme).toMatch(/jev_acceptance_gate/);
    expect(readme).toMatch(/Fail-open, never fail-catch/);
    expect(readme).toMatch(/SemetricLabs\/omp-greenlight/);
    expect(readme).toMatch(/0\/94/);
    expect(readme).toMatch(/never tunes its own threshold/);
    expect(readme).toMatch(/[Gg]raded allow/);
    expect(readme).toMatch(/Permission ≠ probability/);
    expect(readme).toMatch(/ThyFriendlyFox\/jev-triage/);
    expect(readme).toMatch(/teacher of record/);
    expect(readme).toMatch(/mallahyari\/system-one-benchmark/);
    expect(readme).toMatch(/90\.9%/);
    expect(readme).toMatch(/uncalibrated open PCD/);
    expect(readme).toMatch(/collapseindex\/dinostomp/);
    expect(readme).toMatch(/check the instrument first/);
    expect(readme).toMatch(/mrmps\/classifier-dev/);
    expect(readme).toMatch(/FALLBACK/);
    expect(readme).toMatch(/0\.546/);
    expect(readme).toMatch(/Undeclared fallback = eval integrity failure/);
    expect(readme).toMatch(/godspede\/construct-auto-classifier/);
    expect(readme).toMatch(/0 dangerous/);
    expect(readme).toMatch(/Privilege Is Not a Verdict/);
    expect(readme).toMatch(/data_loss/);
    expect(readme).toMatch(/minConfidence/);
    expect(readme).toMatch(/omkarghugarkar007\/actiongate-jev/);
    expect(readme).toMatch(/Jev supplies evidence/);
    expect(readme).toMatch(/Code owns authority/);
    expect(readme).toMatch(/never overrides/);
    expect(readme).toMatch(/Schema-valid ≠ intent-matched/);
    expect(readme).toMatch(/single-use Action Grant/);
    expect(readme).toMatch(/replayed/);
    expect(readme).toMatch(/wrapTool/);
    expect(readme).toMatch(/reddpy\/AgentGhost/);
    expect(readme).toMatch(/@agentghost\/sdk/);
    expect(readme).toMatch(/tool's execution function/);
    expect(readme).toMatch(/silently skipped/);
    expect(readme).toMatch(/failMode/);
    expect(readme).toMatch(/Nyarlathoteppppp\/pi-heed/);
    expect(readme).toMatch(/instruction-drift/);
    expect(readme).toMatch(/context compaction/);
    expect(readme).toMatch(/Reindeer-AI\/pi-jev-guard/);
    expect(readme).toMatch(/informative/);
    expect(readme).toMatch(/violationThreshold/);
    expect(readme).toMatch(/goodruizhan\/pi-jev-control/);
    expect(readme).toMatch(/control plane/);
    expect(readme).toMatch(/never force-click/);
    expect(readme).toMatch(/shitianfang\/jev-use/);
    expect(readme).toMatch(/jev_gate/);
    expect(readme).toMatch(/only ever tightens/);
    expect(readme).toMatch(/12\/12 correct/);
    expect(readme).toMatch(/jimmyhealer\/jevex/);
    expect(readme).toMatch(/what to read/);
    expect(readme).toMatch(/kbhuw\/jev-sift/);
    expect(readme).toMatch(/yodablocks\/commitjev/);
    expect(readme).toMatch(/not a reason to refuse/);
    expect(readme).toMatch(/IPECTER\/jev-runway/);
    expect(readme).toMatch(/LICENSE only/);
    expect(readme).toMatch(/dev-willbird1936\/pi-jev-compact/);
    expect(readme).toMatch(/keepThreshold/);
    expect(readme).toMatch(/robbyczgw-cla\/hermes-plugin-jev/);
    expect(readme).toMatch(/cannot grant permission/);
    expect(readme).toMatch(/nekowasabi\/jev-routing/);
    expect(readme).toMatch(/1 schema/);
    expect(readme).toMatch(/mrmps\/classifier-dev/);
    expect(readme).toMatch(/advertised backend ≠ served backend/);
    expect(readme).toMatch(/FALLBACK/);
    expect(readme).toMatch(/0\.546/);
    expect(readme).toMatch(/totally-tim\/jev-gate/);
    expect(readme).toMatch(/soft-score-as-hard-rank/);
    expect(readme).toMatch(/connectedGraph\/claude-jev-warden/);
    expect(readme).toMatch(/warden-as-hard-gate/);
    expect(readme).toMatch(/attention≠verdict/);
    expect(readme).toMatch(/jonathanavis96\/jev-kit/);
    expect(readme).toMatch(/This is not a security control/);
    expect(readme).toMatch(/airlock-ok/);
    expect(readme).toMatch(/agent-chaperone\/agent-chaperone/);
    expect(readme).toMatch(/discarded without complaint/);
    expect(readme).toMatch(/0\.976/);
    expect(readme).toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(readme).toMatch(/system directive, not a hard block/);
    expect(readme).toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(readme).toMatch(/tamaratran\/fast-jev-compaction/);
    expect(readme).toMatch(/removedMessages/);
    expect(readme).toMatch(/riz007\/yolo-shell/);
    expect(readme).toMatch(/no silent fail-open when Jev is down/);
    expect(readme).toMatch(/YOLO_BYPASS/);
    expect(readme).toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(readme).toMatch(/Command sent ≠ state confirmed/);
    expect(readme).toMatch(/action ≠ verified outcome/);
    expect(readme).toMatch(/muthuishere\/herdr-jev/);
    expect(readme).toMatch(/Nothing here works yet/);
    expect(readme).toMatch(/AlexWortega\/openjev/);
    expect(readme).toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(readme).toMatch(/advertised capability ≠ shipped module/);
    expect(readme).toMatch(/shadow vs live/);
    expect(readme).toMatch(/shadow_noop/);
    expect(readme).toMatch(/alsoleg89\/jev-guard/);
    expect(readme).toMatch(/Tripwires never deny/);
    expect(readme).toMatch(/pablozr\/JevGuard/);
    expect(readme).toMatch(/never turns incomplete evidence/);
    expect(readme).toMatch(/advertised monorepo ≠ shipped packages/);
    expect(readme).toMatch(/ybadragon\/jev-proving-ground/);
    expect(readme).toMatch(/planted defect/);
    expect(readme).toMatch(/verify-criteria/);
    expect(readme).toMatch(/Synxneuos\/jevbrain/);
    expect(readme).toMatch(/AUTO_ACT/);
    expect(readme).toMatch(/REVIEW_QUEUE/);
    expect(readme).toMatch(/russfranky\/jev-crawlers/);
    expect(readme).toMatch(/unverified lead/);
    expect(readme).toMatch(/ranking signals/);
    expect(readme).toMatch(/githubnext\/localjev/);
    expect(readme).toMatch(/consequential decisions/);
    expect(readme).toMatch(/NandhaKishorM\/laya/);
    expect(readme).toMatch(/95\.2%/);
    expect(readme).toMatch(/ThyFriendlyFox\/jev-curate/);
    expect(readme).toMatch(/curated\.jsonl/);
    expect(readme).toMatch(/rejected\.jsonl/);
    expect(readme).toMatch(/ohernandezdev\/jev-pr-review/);
    expect(readme).toMatch(/Shadow-mode only/);
    expect(readme).toMatch(/soundness theater/);
    expect(readme).toMatch(/zyphr-labs\/turnstile/);
    expect(readme).toMatch(/Jev never grants authority/);
    expect(readme).toMatch(/copyleftdev\/jev-labs/);
    expect(readme).toMatch(/Never confidently wrong/);
    expect(readme).toMatch(/Reasonofmoon\/seal/);
    expect(readme).toMatch(/coverage ledger/);
    expect(readme).toMatch(/Hiding escalations is a product lie/);
    expect(readme).toMatch(/schema-valid ≠ semantically correct/);
    expect(readme).toMatch(/mint ≠ product brain/);
    expect(readme).toMatch(/Zaious\/jev-capability-atlas/);
    expect(readme).toMatch(/hold-vs-break/);
    expect(readme).toMatch(/type-safe ≠ correct/);
    expect(readme).toMatch(/scienthoon\/jev-ood-calibration/);
    expect(readme).toMatch(/AUC ≠ ECE/);
    expect(readme).toMatch(/noise floor/);
    expect(readme).toMatch(/adarc8\/how-sure-is-jev/);
    expect(readme).toMatch(/edwardyen724-g\/jev-compactor/);
    expect(readme).toMatch(/regex floor/);
    expect(readme).toMatch(/dtduc-git\/jev-packs/);
    expect(readme).toMatch(/evidence-gated/);
    expect(readme).toMatch(/NemanjaManic\/ci-gatekeeper-bot-jev/);
    expect(readme).toMatch(/Vercel AI Gateway/);
    expect(readme).toMatch(/should_review/);
    expect(readme).toMatch(/touches_secrets/);
    expect(readme).toMatch(/shubhangi013\/prune-review/);
    expect(readme).toMatch(/safety escarpment/);
    expect(readme).toMatch(/yottayoshida\/jev-intent-review/);
    expect(readme).toMatch(/search hint/);
    expect(readme).toMatch(/VERIFIED/);
    expect(readme).toMatch(/VIOLATION/);
    expect(readme).toMatch(/incomplete-change/);
    expect(readme).toMatch(/zeeshan8281\/slo-router/);
    expect(readme).toMatch(/77\.93/);
    expect(readme).toMatch(/490\.38/);
    expect(readme).toMatch(/exactness/);
    expect(readme).toMatch(/rashedInt32\/jev-lens/);
    expect(readme).toMatch(/never blocks/);
    expect(readme).toMatch(/never says green unless/);
    expect(readme).toMatch(/muse0509\/jev-preflight/);
    expect(readme).toMatch(/eight risk axes/);
    expect(readme).toMatch(/0\.85 threshold is uncalibrated/);
    expect(readme).toMatch(/win4r\/jev-security-scan/);
    expect(readme).toMatch(/Unflagged ≠ certified safe/);
    expect(readme).toMatch(/bojansandhaus\/jev-decisions/);
    expect(readme).toMatch(/JEV_ENABLE_HOOKS/);
    expect(readme).toMatch(/failed review grants no permission/);
    expect(readme).toMatch(/TeoMastro\/jev-vs-llm-guardrails-intent-router/);
    expect(readme).toMatch(/96\.8%/);
    expect(readme).toMatch(/classify accuracy is not a safety proof/);
    expect(readme).toMatch(/Hunch:/);
    expect(readme).toMatch(/SargeDev\/jev-gate-student-b/);
    expect(readme).toMatch(/student is not the hard envelope/);
    expect(readme).toMatch(/ickma2311\/jev-baselines-eval/);
    expect(readme).toMatch(/three same-day errata/);
    expect(readme).toMatch(/AMBIGUOUS/);
    expect(readme).toMatch(/Dharundp6\/jev-carryforward/);
    expect(readme).toMatch(/nothing summarised/);
    expect(readme).toMatch(/0\/4/);
    expect(readme).toMatch(/hope the model looks/);
    expect(readme).toMatch(/laurentfabre\/databricks-jev-pdf-lab/);
    expect(readme).toMatch(/no quality-equivalent/);
    expect(readme).toMatch(/suraj-phanindra\/wellposed/);
    expect(readme).toMatch(/never the sole veto/);
    expect(readme).toMatch(/taskset \(score first\)/);
    expect(readme).toMatch(/do not replace a scored taskset/i);
    expect(readme).toMatch(/independent answer keys/i);
    expect(readme).toMatch(/never promote predictions to labels/i);
    expect(readme).toMatch(/correctness ≠ confidence/);
    expect(readme).toMatch(/equivalent case sets/i);
    expect(readme).toMatch(/LLM-as-judge/);
    expect(readme).toMatch(/jevals measures decisions/);
    expect(readme).toMatch(/rh-guard gates agent tool use/);
    expect(readme).toMatch(/Harbor scores product\/agent loops/);
    expect(readme).toMatch(/\*\*practices\*\*, not install dependencies/);
    expect(readme).not.toMatch(/research-prompt/i);
  });

  it("names the product Reward Hack Guard / RH Guard on public surfaces", () => {
    const productPaths = [
      ...PUBLIC_COPY_PATHS,
      "src/app/page.tsx",
      "src/app/layout.tsx",
      "src/components/app-shell.tsx",
      ".claude-plugin/plugin.json",
      ".claude-plugin/marketplace.json",
      "package.json",
    ] as const;
    for (const rel of productPaths) {
      const text = readFileSync(join(root, rel), "utf8");
      expect(text, rel).not.toMatch(/Hack Radar/);
    }
    const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
      name: string;
    };
    expect(pkg.name).toBe("rh-guard");
    const plugin = JSON.parse(
      readFileSync(join(root, ".claude-plugin/plugin.json"), "utf8")
    ) as { displayName: string };
    expect(plugin.displayName).toBe("Reward Hack Guard");
    const shell = readFileSync(join(root, "src/components/app-shell.tsx"), "utf8");
    expect(shell).toMatch(/>\s*RH Guard\s*</);
  });

  it("does not add Abide as a runtime dependency", () => {
    const pkg = readFileSync(join(root, "package.json"), "utf8");
    const lock = readFileSync(join(root, "package-lock.json"), "utf8");
    expect(pkg).not.toMatch(/abide/i);
    expect(lock).not.toMatch(/@coldtea\/abide/);
  });

  it("does not add hourly sibling watches as runtime dependencies", () => {
    const pkg = readFileSync(join(root, "package.json"), "utf8");
    const lock = readFileSync(join(root, "package-lock.json"), "utf8");
    expect(pkg).not.toMatch(/pi-jev-approver/);
    expect(pkg).not.toMatch(/agent-workflow-typesafe/);
    expect(pkg).not.toMatch(/jevscan/);
    expect(pkg).not.toMatch(/jev-testbench/);
    expect(pkg).not.toMatch(/semantic-firewall/);
    expect(pkg).not.toMatch(/claude-code-jev/);
    expect(pkg).not.toMatch(/jev-agent-safety-arena/);
    expect(pkg).not.toMatch(/jev-model-router/);
    expect(pkg).not.toMatch(/gliner25-compaction/);
    expect(pkg).not.toMatch(/latch/);
    expect(pkg).not.toMatch(/clear-head/);
    expect(pkg).not.toMatch(/jev-marshal/);
    expect(pkg).not.toMatch(/wakegate/);
    expect(pkg).not.toMatch(/if-ai/);
    expect(pkg).not.toMatch(/omp-auto-mode/);
    expect(pkg).not.toMatch(/toolgate/);
    expect(pkg).not.toMatch(/jev-reviewer/);
    expect(pkg).not.toMatch(/safe-sh/);
    expect(pkg).not.toMatch(/interlock/);
    expect(pkg).not.toMatch(/port-cleanup/);
    expect(pkg).not.toMatch(/jev-dspy-control-plane/);
    expect(pkg).not.toMatch(/jev-arena/);
    expect(pkg).not.toMatch(/cmdc-auto-mode/);
    expect(pkg).not.toMatch(/firehose-judge/);
    expect(pkg).not.toMatch(/jav-email-cascade/);
    expect(pkg).not.toMatch(/waymode/);
    expect(pkg).not.toMatch(/jev-gate-student-b/);
    expect(pkg).not.toMatch(/omp-jev-extensions/);
    expect(pkg).not.toMatch(/omp-greenlight/);
    expect(pkg).not.toMatch(/skill-broker/);
    expect(pkg).not.toMatch(/dinostomp/);
    expect(pkg).not.toMatch(/classifier-dev/);
    expect(pkg).not.toMatch(/jev-kit/);
    expect(pkg).not.toMatch(/agent-chaperone/);
    expect(pkg).not.toMatch(/opencode-intent-gate/);
    expect(pkg).not.toMatch(/opencode-context-pruner/);
    expect(pkg).not.toMatch(/fast-jev-compaction/);
    expect(pkg).not.toMatch(/yolo-shell/);
    expect(pkg).not.toMatch(/jev-home-assistant-sentinel/);
    expect(pkg).not.toMatch(/herdr-jev/);
    expect(pkg).not.toMatch(/apa-agent-harness/);
    expect(pkg).not.toMatch(/@aipersona\/agent-harness/);
    expect(pkg).not.toMatch(/alsoleg89\/jev-guard/);
    expect(pkg).not.toMatch(/pablozr\/JevGuard/);
    expect(pkg).not.toMatch(/jev-proving-ground/);
    expect(pkg).not.toMatch(/jevbrain/);
    expect(pkg).not.toMatch(/jev-crawlers/);
    expect(pkg).not.toMatch(/construct-auto-classifier/);
    expect(pkg).not.toMatch(/actiongate-jev/);
    expect(pkg).not.toMatch(/AgentGhost/);
    expect(pkg).not.toMatch(/@agentghost\/sdk/);
    expect(pkg).not.toMatch(/pi-heed/);
    expect(pkg).not.toMatch(/pi-jev-guard/);
    expect(pkg).not.toMatch(/pi-jev-control/);
    expect(pkg).not.toMatch(/jev-use/);
    expect(pkg).not.toMatch(/jimmyhealer\/jevex/);
    expect(pkg).not.toMatch(/commitjev/);
    expect(pkg).not.toMatch(/jev-runway/);
    expect(pkg).not.toMatch(/pi-jev-compact/);
    expect(pkg).not.toMatch(/hermes-plugin-jev/);
    expect(pkg).not.toMatch(/jev-routing/);
    expect(pkg).not.toMatch(/mrmps\/classifier-dev/);
    expect(pkg).not.toMatch(/totally-tim\/jev-gate/);
    expect(pkg).not.toMatch(/connectedGraph\/claude-jev-warden/);
    expect(pkg).not.toMatch(/jonathanavis96\/jev-kit/);
    expect(pkg).not.toMatch(/agent-chaperone\/agent-chaperone/);
    expect(pkg).not.toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(pkg).not.toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(pkg).not.toMatch(/tamaratran\/fast-jev-compaction/);
    expect(pkg).not.toMatch(/riz007\/yolo-shell/);
    expect(pkg).not.toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(pkg).not.toMatch(/muthuishere\/herdr-jev/);
    expect(pkg).not.toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(pkg).not.toMatch(/alsoleg89\/jev-guard/);
    expect(pkg).not.toMatch(/pablozr\/JevGuard/);
    expect(pkg).not.toMatch(/ybadragon\/jev-proving-ground/);
    expect(pkg).not.toMatch(/Synxneuos\/jevbrain/);
    expect(pkg).not.toMatch(/russfranky\/jev-crawlers/);
    expect(pkg).not.toMatch(/githubnext\/localjev/);
    expect(pkg).not.toMatch(/NandhaKishorM\/laya/);
    expect(pkg).not.toMatch(/jev-sift/);
    expect(pkg).not.toMatch(/jev-curate/);
    expect(pkg).not.toMatch(/jev-pr-review/);
    expect(pkg).not.toMatch(/slo-router/);
    expect(pkg).not.toMatch(/jev-lens/);
    expect(pkg).not.toMatch(/jev-preflight/);
    expect(pkg).not.toMatch(/jev-security-scan/);
    expect(pkg).not.toMatch(/jev-decisions/);
    expect(pkg).not.toMatch(/jev-vs-llm-guardrails-intent-router/);
    expect(pkg).not.toMatch(/jev-compactor/);
    expect(pkg).not.toMatch(/jev-packs/);
    expect(pkg).not.toMatch(/ci-gatekeeper-bot-jev/);
    expect(pkg).not.toMatch(/zyphr-labs\/turnstile/);
    expect(pkg).not.toMatch(/jev-labs/);
    expect(pkg).not.toMatch(/Reasonofmoon\/seal/);
    expect(pkg).not.toMatch(/how-sure-is-jev/);
    expect(pkg).not.toMatch(/jev-capability-atlas/);
    expect(pkg).not.toMatch(/jev-ood-calibration/);
    expect(pkg).not.toMatch(/prune-review/);
    expect(pkg).not.toMatch(/jev-intent-review/);
    expect(pkg).not.toMatch(/jev-triage/);
    expect(pkg).not.toMatch(/system-one-benchmark/);
    expect(pkg).not.toMatch(/jev-baselines-eval/);
    expect(pkg).not.toMatch(/jev-carryforward/);
    expect(pkg).not.toMatch(/databricks-jev-pdf-lab/);
    expect(lock).not.toMatch(/pi-jev-approver/);
    expect(lock).not.toMatch(/agent-workflow-typesafe/);
    expect(lock).not.toMatch(/jevscan/);
    expect(lock).not.toMatch(/jev-testbench/);
    expect(lock).not.toMatch(/semantic-firewall/);
    expect(lock).not.toMatch(/claude-code-jev/);
    expect(lock).not.toMatch(/jev-agent-safety-arena/);
    expect(lock).not.toMatch(/jev-model-router/);
    expect(lock).not.toMatch(/gliner25-compaction/);
    expect(lock).not.toMatch(/latch/);
    expect(lock).not.toMatch(/clear-head/);
    expect(lock).not.toMatch(/jev-marshal/);
    expect(lock).not.toMatch(/wakegate/);
    expect(lock).not.toMatch(/if-ai/);
    expect(lock).not.toMatch(/omp-auto-mode/);
    expect(lock).not.toMatch(/toolgate/);
    expect(lock).not.toMatch(/jev-reviewer/);
    expect(lock).not.toMatch(/safe-sh/);
    expect(lock).not.toMatch(/interlock/);
    expect(lock).not.toMatch(/port-cleanup/);
    expect(lock).not.toMatch(/jev-dspy-control-plane/);
    expect(lock).not.toMatch(/jev-arena/);
    expect(lock).not.toMatch(/cmdc-auto-mode/);
    expect(lock).not.toMatch(/firehose-judge/);
    expect(lock).not.toMatch(/jav-email-cascade/);
    expect(lock).not.toMatch(/waymode/);
    expect(lock).not.toMatch(/jev-gate-student-b/);
    expect(lock).not.toMatch(/omp-jev-extensions/);
    expect(lock).not.toMatch(/omp-greenlight/);
    expect(lock).not.toMatch(/skill-broker/);
    expect(lock).not.toMatch(/dinostomp/);
    expect(lock).not.toMatch(/classifier-dev/);
    expect(lock).not.toMatch(/jev-kit/);
    expect(lock).not.toMatch(/agent-chaperone/);
    expect(lock).not.toMatch(/opencode-intent-gate/);
    expect(lock).not.toMatch(/opencode-context-pruner/);
    expect(lock).not.toMatch(/fast-jev-compaction/);
    expect(lock).not.toMatch(/yolo-shell/);
    expect(lock).not.toMatch(/jev-home-assistant-sentinel/);
    expect(lock).not.toMatch(/herdr-jev/);
    expect(lock).not.toMatch(/apa-agent-harness/);
    expect(lock).not.toMatch(/@aipersona\/agent-harness/);
    expect(lock).not.toMatch(/alsoleg89\/jev-guard/);
    expect(lock).not.toMatch(/pablozr\/JevGuard/);
    expect(lock).not.toMatch(/jev-proving-ground/);
    expect(lock).not.toMatch(/jevbrain/);
    expect(lock).not.toMatch(/jev-crawlers/);
    expect(lock).not.toMatch(/construct-auto-classifier/);
    expect(lock).not.toMatch(/actiongate-jev/);
    expect(lock).not.toMatch(/AgentGhost/);
    expect(lock).not.toMatch(/@agentghost\/sdk/);
    expect(lock).not.toMatch(/pi-heed/);
    expect(lock).not.toMatch(/pi-jev-guard/);
    expect(lock).not.toMatch(/pi-jev-control/);
    expect(lock).not.toMatch(/jev-use/);
    expect(lock).not.toMatch(/jimmyhealer\/jevex/);
    expect(lock).not.toMatch(/commitjev/);
    expect(lock).not.toMatch(/jev-runway/);
    expect(lock).not.toMatch(/pi-jev-compact/);
    expect(lock).not.toMatch(/hermes-plugin-jev/);
    expect(lock).not.toMatch(/jev-routing/);
    expect(lock).not.toMatch(/mrmps\/classifier-dev/);
    expect(lock).not.toMatch(/totally-tim\/jev-gate/);
    expect(lock).not.toMatch(/connectedGraph\/claude-jev-warden/);
    expect(lock).not.toMatch(/jonathanavis96\/jev-kit/);
    expect(lock).not.toMatch(/agent-chaperone\/agent-chaperone/);
    expect(lock).not.toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(lock).not.toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(lock).not.toMatch(/tamaratran\/fast-jev-compaction/);
    expect(lock).not.toMatch(/riz007\/yolo-shell/);
    expect(lock).not.toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(lock).not.toMatch(/muthuishere\/herdr-jev/);
    expect(lock).not.toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(lock).not.toMatch(/alsoleg89\/jev-guard/);
    expect(lock).not.toMatch(/pablozr\/JevGuard/);
    expect(lock).not.toMatch(/ybadragon\/jev-proving-ground/);
    expect(lock).not.toMatch(/Synxneuos\/jevbrain/);
    expect(lock).not.toMatch(/russfranky\/jev-crawlers/);
    expect(lock).not.toMatch(/githubnext\/localjev/);
    expect(lock).not.toMatch(/NandhaKishorM\/laya/);
    expect(lock).not.toMatch(/jev-sift/);
    expect(lock).not.toMatch(/jev-curate/);
    expect(lock).not.toMatch(/jev-pr-review/);
    expect(lock).not.toMatch(/slo-router/);
    expect(lock).not.toMatch(/jev-lens/);
    expect(lock).not.toMatch(/jev-preflight/);
    expect(lock).not.toMatch(/jev-security-scan/);
    expect(lock).not.toMatch(/jev-decisions/);
    expect(lock).not.toMatch(/jev-vs-llm-guardrails-intent-router/);
    expect(lock).not.toMatch(/jev-compactor/);
    expect(lock).not.toMatch(/jev-packs/);
    expect(lock).not.toMatch(/ci-gatekeeper-bot-jev/);
    expect(lock).not.toMatch(/zyphr-labs\/turnstile/);
    expect(lock).not.toMatch(/jev-labs/);
    expect(lock).not.toMatch(/Reasonofmoon\/seal/);
    expect(lock).not.toMatch(/how-sure-is-jev/);
    expect(lock).not.toMatch(/jev-capability-atlas/);
    expect(lock).not.toMatch(/jev-ood-calibration/);
    expect(lock).not.toMatch(/prune-review/);
    expect(lock).not.toMatch(/jev-intent-review/);
    expect(lock).not.toMatch(/jev-triage/);
    expect(lock).not.toMatch(/system-one-benchmark/);
    expect(lock).not.toMatch(/jev-baselines-eval/);
    expect(lock).not.toMatch(/jev-carryforward/);
    expect(lock).not.toMatch(/databricks-jev-pdf-lab/);
  });

  it("does not advertise Deep Research paste workflows on public surfaces", () => {
    for (const rel of PUBLIC_COPY_PATHS) {
      const text = readFileSync(join(root, rel), "utf8");
      expect(text, rel).not.toMatch(RESEARCH_OPS_CLUTTER);
    }
  });

  it("does not call the GitHub copy private", () => {
    const readme = readFileSync(join(root, "README.md"), "utf8");
    expect(readme).not.toMatch(/Both copies are private/i);
    expect(readme).toMatch(/public on GitHub/i);
    expect(readme).toMatch(/24601\/Augustus/);
    expect(readme).toMatch(/examples\/claude-settings\.json/);
    expect(readme).toMatch(/examples\/cursor-hooks\.json/);
    expect(readme).toMatch(/docs\/hosts\.md/);
    expect(readme).toMatch(/Codex/);
    expect(readme).toMatch(/DeepSeek Harness/);
    expect(readme).toMatch(/support via ToolRuntime wrap/i);
  });

  it("ships a thin rh-guard skill that refuses to be a Next runbook", () => {
    const skill = readFileSync(
      join(root, ".agents/skills/rh-guard/SKILL.md"),
      "utf8"
    );
    expect(skill).toMatch(/^name: rh-guard/m);
    expect(skill).toMatch(/Reward Hack Guard/);
    expect(skill).toMatch(/RH Guard/);
    expect(skill).not.toMatch(/Hack Radar/);
    expect(skill).toMatch(/Do not use to run or debug the Next\.js/i);
    expect(skill).toMatch(/npx skills add 24601\/rh-guard --skill rh-guard/);
    expect(skill).toMatch(/opaque denials for agents/i);
    expect(skill).toMatch(/Never train RL/i);
    expect(skill).toMatch(/high means the hack is present/i);
    expect(skill).toMatch(/control_falsifier_named/);
    expect(skill).toMatch(/multi-host/);
    expect(skill).toMatch(/Codex/);
    expect(skill).toMatch(/docs\/hosts\.md/);
    expect(skill).toMatch(/ToolRuntime/);
    expect(skill).toMatch(/thevibeworks\/jevgate/);
    expect(skill).toMatch(/allowlist proves what may run/i);
    expect(skill).toMatch(/fastino-ai\/GLiGuard/);
    expect(skill).toMatch(/coldteadotai\/abide/);
    expect(skill).toMatch(/soft\s+project-instruction/);
    expect(skill).toMatch(/banded confidence/);
    expect(skill).toMatch(/Abide does not catch reward hacking/);
    expect(skill).toMatch(/Harbor\/jevals-adjacent measurement discipline/);
    expect(skill).toMatch(/Eval integrity & measurement/);
    expect(skill).toMatch(/harbor-framework\/harbor/);
    expect(skill).toMatch(/dayhaysoos\/jevals/);
    expect(skill).toMatch(/memovai\/openevals/);
    expect(skill).toMatch(/cheap parallel/);
    expect(skill).toMatch(/caiovicentino\/jev-align/);
    expect(skill).toMatch(/AntonioCoppe\/jev-harness/);
    expect(skill).toMatch(/phin-tech\/pi-jev-approver/);
    expect(skill).toMatch(/commandRules/);
    expect(skill).toMatch(/ngallodev-software\/agent-workflow-typesafe-ai/);
    expect(skill).toMatch(/never changes host routing\/executor/);
    expect(skill).toMatch(/alexykn\/jevscan/);
    expect(skill).toMatch(/tree-sitter extract/);
    expect(skill).toMatch(/ufx7\/jev-testbench/);
    expect(skill).toMatch(/llm_autonomous/);
    expect(skill).toMatch(/scripted_plus_jev/);
    expect(skill).toMatch(/llm_plus_jev/);
    expect(skill).toMatch(/do not claim collab helps without arms/);
    expect(skill).toMatch(/CeamKrier\/semantic-firewall/);
    expect(skill).toMatch(/skip-when-absent/);
    expect(skill).toMatch(/hard envelope stays structural/);
    expect(skill).toMatch(/RahulBalakavi\/claude-code-jev/);
    expect(skill).toMatch(/230\.8ms p50/);
    expect(skill).toMatch(/263\.9ms mean/);
    expect(skill).toMatch(/mjyoke1111\/jev-agent-safety-arena/);
    expect(skill).toMatch(/Mandrilsquad1441\/jev-model-router/);
    expect(skill).toMatch(/not a rh-guard peer/);
    expect(skill).toMatch(/m-newhauser\/gliner25-compaction/);
    expect(skill).toMatch(/fastino\/gliner2\.5-base-v1/);
    expect(skill).toMatch(/character-offset/);
    expect(skill).toMatch(/keep_full/);
    expect(skill).toMatch(/shadowMode/);
    expect(skill).toMatch(/hard shell\/mutation policy overrides the soft model/);
    expect(skill).toMatch(/Not reward-hack detection/);
    expect(skill).toMatch(/fail-closed retention vs fail-open rest/);
    expect(skill).toMatch(/CaseReed\/latch/);
    expect(skill).toMatch(/Gate: PASS/);
    expect(skill).toMatch(/Gate: BLOCK/);
    expect(skill).toMatch(/ignore_as_infra/);
    expect(skill).toMatch(/VladyslavHontar\/clear-head/);
    expect(skill).toMatch(/CONTRADICTED/);
    expect(skill).toMatch(/LightningK0ala\/jev-marshal/);
    expect(skill).toMatch(/empty public tree at capture/);
    expect(skill).toMatch(/Victor-Casado\/if-ai/);
    expect(skill).toMatch(/shitianfang\/wakegate/);
    expect(skill).toMatch(/fail-open wake gate/);
    expect(skill).toMatch(/alexsatch\/omp-auto-mode/);
    expect(skill).toMatch(/fdemir\/toolgate/);
    expect(skill).toMatch(/ndolinschi\/toolgate/);
    expect(skill).toMatch(/`allow` \/ `block` \/ `review`/);
    expect(skill).toMatch(/given → expected → actual/);
    expect(skill).toMatch(/egma-ai\/jev-reviewer/);
    expect(skill).toMatch(/attention priorities/);
    expect(skill).toMatch(/blocked as unsafe/);
    expect(skill).toMatch(/EpicEric\/safe-sh/);
    expect(skill).toMatch(/static shell/);
    expect(skill).toMatch(/somoore\/interlock/);
    expect(skill).toMatch(/secrets never enter the agent/);
    expect(skill).toMatch(/38-case/);
    expect(skill).toMatch(/not a blind paper/);
    expect(skill).toMatch(/epiphany-dynamics\/port-cleanup/);
    expect(skill).toMatch(/identity re-check before SIGTERM/);
    expect(skill).toMatch(/app-owned explanation text/);
    expect(skill).toMatch(/manikanda-kumar\/jev-dspy-control-plane/);
    expect(skill).toMatch(/cannot add routes or tools/);
    expect(skill).toMatch(/meetr1912\/jev-arena/);
    expect(skill).toMatch(/overconfident in the low bins/);
    expect(skill).toMatch(/mja00\/cmdc-auto-mode/);
    expect(skill).toMatch(/beforeToolCall/);
    expect(skill).toMatch(/within_scope ≤ 0\.25/);
    expect(skill).toMatch(/auto-fail-closed/);
    expect(skill).toMatch(/ragelink\/firehose-judge/);
    expect(skill).toMatch(/needs a human/);
    expect(skill).toMatch(/skiingfalcon\/jav-email-cascade/);
    expect(skill).toMatch(/decide → policy → LLM leftover/);
    expect(skill).toMatch(/injection_suspected/);
    expect(skill).toMatch(/cannot tell/);
    expect(skill).toMatch(/never rounded/);
    expect(skill).toMatch(/mossburgh\/waymode/);
    expect(skill).toMatch(/typed actions/);
    expect(skill).toMatch(/retained evidence/);
    expect(skill).toMatch(/Jev confidence grants no permission/);
    expect(skill).toMatch(/adamjralph\/skill-broker/);
    expect(skill).toMatch(/never grants access/);
    expect(skill).toMatch(/luw2007\/omp-jev-extensions/);
    expect(skill).toMatch(/jev_acceptance_gate/);
    expect(skill).toMatch(/Fail-open, never fail-catch/);
    expect(skill).toMatch(/SemetricLabs\/omp-greenlight/);
    expect(skill).toMatch(/0\/94/);
    expect(skill).toMatch(/never tunes its own threshold/);
    expect(skill).toMatch(/[Gg]raded allow/);
    expect(skill).toMatch(/Permission ≠ probability/);
    expect(skill).toMatch(/ThyFriendlyFox\/jev-triage/);
    expect(skill).toMatch(/teacher of record/);
    expect(skill).toMatch(/mallahyari\/system-one-benchmark/);
    expect(skill).toMatch(/90\.9%/);
    expect(skill).toMatch(/uncalibrated open PCD/);
    expect(skill).toMatch(/collapseindex\/dinostomp/);
    expect(skill).toMatch(/mrmps\/classifier-dev/);
    expect(skill).toMatch(/FALLBACK/);
    expect(skill).toMatch(/0\.546/);
    expect(skill).toMatch(/Undeclared fallback = eval integrity failure/);
    expect(skill).toMatch(/check the instrument first/);
    expect(skill).toMatch(/godspede\/construct-auto-classifier/);
    expect(skill).toMatch(/0 dangerous/);
    expect(skill).toMatch(/Privilege Is Not a Verdict/);
    expect(skill).toMatch(/data_loss/);
    expect(skill).toMatch(/minConfidence/);
    expect(skill).toMatch(/omkarghugarkar007\/actiongate-jev/);
    expect(skill).toMatch(/Jev supplies evidence/);
    expect(skill).toMatch(/Code owns authority/);
    expect(skill).toMatch(/never overrides/);
    expect(skill).toMatch(/Schema-valid ≠ intent-matched/);
    expect(skill).toMatch(/single-use Action Grant/);
    expect(skill).toMatch(/replayed/);
    expect(skill).toMatch(/wrapTool/);
    expect(skill).toMatch(/reddpy\/AgentGhost/);
    expect(skill).toMatch(/@agentghost\/sdk/);
    expect(skill).toMatch(/tool's execution function/);
    expect(skill).toMatch(/silently skipped/);
    expect(skill).toMatch(/failMode/);
    expect(skill).toMatch(/Nyarlathoteppppp\/pi-heed/);
    expect(skill).toMatch(/instruction-drift/);
    expect(skill).toMatch(/context compaction/);
    expect(skill).toMatch(/Reindeer-AI\/pi-jev-guard/);
    expect(skill).toMatch(/informative/);
    expect(skill).toMatch(/violationThreshold/);
    expect(skill).toMatch(/goodruizhan\/pi-jev-control/);
    expect(skill).toMatch(/control plane/);
    expect(skill).toMatch(/never force-click/);
    expect(skill).toMatch(/shitianfang\/jev-use/);
    expect(skill).toMatch(/jev_gate/);
    expect(skill).toMatch(/only ever tightens/);
    expect(skill).toMatch(/12\/12 correct/);
    expect(skill).toMatch(/jimmyhealer\/jevex/);
    expect(skill).toMatch(/what to read/);
    expect(skill).toMatch(/kbhuw\/jev-sift/);
    expect(skill).toMatch(/yodablocks\/commitjev/);
    expect(skill).toMatch(/not a reason to refuse/);
    expect(skill).toMatch(/IPECTER\/jev-runway/);
    expect(skill).toMatch(/LICENSE only/);
    expect(skill).toMatch(/dev-willbird1936\/pi-jev-compact/);
    expect(skill).toMatch(/keepThreshold/);
    expect(skill).toMatch(/robbyczgw-cla\/hermes-plugin-jev/);
    expect(skill).toMatch(/cannot grant permission/);
    expect(skill).toMatch(/nekowasabi\/jev-routing/);
    expect(skill).toMatch(/1 schema/);
    expect(skill).toMatch(/mrmps\/classifier-dev/);
    expect(skill).toMatch(/advertised backend ≠ served backend/);
    expect(skill).toMatch(/FALLBACK/);
    expect(skill).toMatch(/0\.546/);
    expect(skill).toMatch(/totally-tim\/jev-gate/);
    expect(skill).toMatch(/soft-score-as-hard-rank/);
    expect(skill).toMatch(/connectedGraph\/claude-jev-warden/);
    expect(skill).toMatch(/warden-as-hard-gate/);
    expect(skill).toMatch(/attention≠verdict/);
    expect(skill).toMatch(/jonathanavis96\/jev-kit/);
    expect(skill).toMatch(/This is not a security control/);
    expect(skill).toMatch(/airlock-ok/);
    expect(skill).toMatch(/agent-chaperone\/agent-chaperone/);
    expect(skill).toMatch(/discarded without complaint/);
    expect(skill).toMatch(/0\.976/);
    expect(skill).toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(skill).toMatch(/system directive, not a hard block/);
    expect(skill).toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(skill).toMatch(/tamaratran\/fast-jev-compaction/);
    expect(skill).toMatch(/removedMessages/);
    expect(skill).toMatch(/riz007\/yolo-shell/);
    expect(skill).toMatch(/no silent fail-open when Jev is down/);
    expect(skill).toMatch(/YOLO_BYPASS/);
    expect(skill).toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(skill).toMatch(/Command sent ≠ state confirmed/);
    expect(skill).toMatch(/action ≠ verified outcome/);
    expect(skill).toMatch(/muthuishere\/herdr-jev/);
    expect(skill).toMatch(/Nothing here works yet/);
    expect(skill).toMatch(/AlexWortega\/openjev/);
    expect(skill).toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(skill).toMatch(/advertised capability ≠ shipped module/);
    expect(skill).toMatch(/shadow vs live/);
    expect(skill).toMatch(/shadow_noop/);
    expect(skill).toMatch(/alsoleg89\/jev-guard/);
    expect(skill).toMatch(/Tripwires never deny/);
    expect(skill).toMatch(/pablozr\/JevGuard/);
    expect(skill).toMatch(/never turns incomplete evidence/);
    expect(skill).toMatch(/advertised monorepo ≠ shipped packages/);
    expect(skill).toMatch(/ybadragon\/jev-proving-ground/);
    expect(skill).toMatch(/planted defect/);
    expect(skill).toMatch(/verify-criteria/);
    expect(skill).toMatch(/Synxneuos\/jevbrain/);
    expect(skill).toMatch(/AUTO_ACT/);
    expect(skill).toMatch(/REVIEW_QUEUE/);
    expect(skill).toMatch(/russfranky\/jev-crawlers/);
    expect(skill).toMatch(/unverified lead/);
    expect(skill).toMatch(/ranking signals/);
    expect(skill).toMatch(/githubnext\/localjev/);
    expect(skill).toMatch(/consequential decisions/);
    expect(skill).toMatch(/NandhaKishorM\/laya/);
    expect(skill).toMatch(/95\.2%/);
    expect(skill).toMatch(/ThyFriendlyFox\/jev-curate/);
    expect(skill).toMatch(/curated\.jsonl/);
    expect(skill).toMatch(/rejected\.jsonl/);
    expect(skill).toMatch(/ohernandezdev\/jev-pr-review/);
    expect(skill).toMatch(/Shadow-mode only/);
    expect(skill).toMatch(/zyphr-labs\/turnstile/);
    expect(skill).toMatch(/Jev never grants authority/);
    expect(skill).toMatch(/copyleftdev\/jev-labs/);
    expect(skill).toMatch(/Never confidently wrong/);
    expect(skill).toMatch(/Reasonofmoon\/seal/);
    expect(skill).toMatch(/coverage ledger/);
    expect(skill).toMatch(/Hiding escalations is a product lie/);
    expect(skill).toMatch(/schema-valid ≠ semantically correct/);
    expect(skill).toMatch(/mint ≠ product brain/);
    expect(skill).toMatch(/Zaious\/jev-capability-atlas/);
    expect(skill).toMatch(/hold-vs-break/);
    expect(skill).toMatch(/type-safe ≠ correct/);
    expect(skill).toMatch(/scienthoon\/jev-ood-calibration/);
    expect(skill).toMatch(/AUC ≠ ECE/);
    expect(skill).toMatch(/noise floor/);
    expect(skill).toMatch(/adarc8\/how-sure-is-jev/);
    expect(skill).toMatch(/edwardyen724-g\/jev-compactor/);
    expect(skill).toMatch(/regex floor/);
    expect(skill).toMatch(/dtduc-git\/jev-packs/);
    expect(skill).toMatch(/evidence-gated/);
    expect(skill).toMatch(/NemanjaManic\/ci-gatekeeper-bot-jev/);
    expect(skill).toMatch(/Vercel AI Gateway/);
    expect(skill).toMatch(/should_review/);
    expect(skill).toMatch(/touches_secrets/);
    expect(skill).toMatch(/shubhangi013\/prune-review/);
    expect(skill).toMatch(/safety escarpment/);
    expect(skill).toMatch(/yottayoshida\/jev-intent-review/);
    expect(skill).toMatch(/search hint/);
    expect(skill).toMatch(/VERIFIED/);
    expect(skill).toMatch(/VIOLATION/);
    expect(skill).toMatch(/incomplete-change/);
    expect(skill).toMatch(/zeeshan8281\/slo-router/);
    expect(skill).toMatch(/77\.93/);
    expect(skill).toMatch(/490\.38/);
    expect(skill).toMatch(/exactness/);
    expect(skill).toMatch(/rashedInt32\/jev-lens/);
    expect(skill).toMatch(/never blocks/);
    expect(skill).toMatch(/never says green unless/);
    expect(skill).toMatch(/muse0509\/jev-preflight/);
    expect(skill).toMatch(/eight risk axes/);
    expect(skill).toMatch(/0\.85 threshold is uncalibrated/);
    expect(skill).toMatch(/win4r\/jev-security-scan/);
    expect(skill).toMatch(/Unflagged ≠ certified safe/);
    expect(skill).toMatch(/bojansandhaus\/jev-decisions/);
    expect(skill).toMatch(/JEV_ENABLE_HOOKS/);
    expect(skill).toMatch(/failed review grants no permission/);
    expect(skill).toMatch(/TeoMastro\/jev-vs-llm-guardrails-intent-router/);
    expect(skill).toMatch(/96\.8%/);
    expect(skill).toMatch(/classify accuracy is not a safety proof/);
    expect(skill).toMatch(/Hunch:/);
    expect(skill).toMatch(/SargeDev\/jev-gate-student-b/);
    expect(skill).toMatch(/student is not the hard envelope/);
    expect(skill).toMatch(/ickma2311\/jev-baselines-eval/);
    expect(skill).toMatch(/three same-day errata/);
    expect(skill).toMatch(/AMBIGUOUS/);
    expect(skill).toMatch(/Dharundp6\/jev-carryforward/);
    expect(skill).toMatch(/nothing summarised/);
    expect(skill).toMatch(/0\/4/);
    expect(skill).toMatch(/hope the model looks/);
    expect(skill).toMatch(/laurentfabre\/databricks-jev-pdf-lab/);
    expect(skill).toMatch(/no quality-equivalent/);
    expect(skill).toMatch(/suraj-phanindra\/wellposed/);
    expect(skill).toMatch(/never the sole veto/);
    expect(skill).toMatch(/do not replace a scored taskset/i);
    expect(skill).toMatch(/independent answer keys/i);
    expect(skill).toMatch(/practices\*\*, not install dependencies/);
  });

  it("keeps Harbor, jevals, and openevals as practices, not hook install deps", () => {
    const evalDoc = readFileSync(join(root, "docs/eval-integrity.md"), "utf8");
    const install = readFileSync(join(root, "docs/install-plugin.md"), "utf8");
    const shape = readFileSync(join(root, "docs/shape.md"), "utf8");
    expect(evalDoc).toMatch(/Eval integrity & measurement/);
    expect(evalDoc).toMatch(/harbor-framework\/harbor/);
    expect(evalDoc).toMatch(/dayhaysoos\/jevals/);
    expect(evalDoc).toMatch(/memovai\/openevals/);
    expect(evalDoc).toMatch(/cheap parallel/);
    expect(evalDoc).toMatch(/wotai-dev\/typesafe-jev-tools/);
    expect(evalDoc).toMatch(/does this decision need a model\?/);
    expect(evalDoc).toMatch(/caiovicentino\/jev-align/);
    expect(evalDoc).toMatch(/AntonioCoppe\/jev-harness/);
    expect(evalDoc).toMatch(/doeixd\/jev-pref/);
    expect(evalDoc).toMatch(/preference-theater/);
    expect(evalDoc).toMatch(/SargeDev\/jev-gate-student-b/);
    expect(evalDoc).toMatch(/Qwen2\.5-0\.5B/);
    expect(evalDoc).toMatch(/luantak\/is-malicious/);
    expect(evalDoc).toMatch(/distill → gate integrity/);
    expect(evalDoc).toMatch(/phin-tech\/pi-jev-approver/);
    expect(evalDoc).toMatch(/commandRules/);
    expect(evalDoc).toMatch(/ngallodev-software\/agent-workflow-typesafe-ai/);
    expect(evalDoc).toMatch(/never changes host routing\/executor/);
    expect(evalDoc).toMatch(/alexykn\/jevscan/);
    expect(evalDoc).toMatch(/tree-sitter extract/);
    expect(evalDoc).toMatch(/ufx7\/jev-testbench/);
    expect(evalDoc).toMatch(/llm_autonomous/);
    expect(evalDoc).toMatch(/scripted_plus_jev/);
    expect(evalDoc).toMatch(/llm_plus_jev/);
    expect(evalDoc).toMatch(/Do not claim collab helps without arms/);
    expect(evalDoc).toMatch(/CeamKrier\/semantic-firewall/);
    expect(evalDoc).toMatch(/goalAlignment/);
    expect(evalDoc).toMatch(/untrustedInstruction/);
    expect(evalDoc).toMatch(/skip-when-absent/);
    expect(evalDoc).toMatch(/ASK_USER/);
    expect(evalDoc).toMatch(/hard envelope stays structural/);
    expect(evalDoc).toMatch(/RahulBalakavi\/claude-code-jev/);
    expect(evalDoc).toMatch(/typesafe\/jev-1\.13/);
    expect(evalDoc).toMatch(/230\.8ms p50/);
    expect(evalDoc).toMatch(/263\.9ms mean/);
    expect(evalDoc).toMatch(/mjyoke1111\/jev-agent-safety-arena/);
    expect(evalDoc).toMatch(/Mandrilsquad1441\/jev-model-router/);
    expect(evalDoc).toMatch(/not a rh-guard peer/);
    expect(evalDoc).toMatch(/m-newhauser\/gliner25-compaction/);
    expect(evalDoc).toMatch(/fastino\/gliner2\.5-base-v1/);
    expect(evalDoc).toMatch(/character-offset/);
    expect(evalDoc).toMatch(/keep_full/);
    expect(evalDoc).toMatch(/shadowMode/);
    expect(evalDoc).toMatch(/[Hh]ard shell\/mutation policy overrides the soft model/);
    expect(evalDoc).toMatch(/not reward-hack detection/);
    expect(evalDoc).toMatch(/fail-closed retention vs fail-open rest/);
    expect(evalDoc).toMatch(/CaseReed\/latch/);
    expect(evalDoc).toMatch(/Gate: PASS/);
    expect(evalDoc).toMatch(/Gate: BLOCK/);
    expect(evalDoc).toMatch(/ignore_as_infra/);
    expect(evalDoc).toMatch(/env_cascade/);
    expect(evalDoc).toMatch(/VladyslavHontar\/clear-head/);
    expect(evalDoc).toMatch(/CONTRADICTED/);
    expect(evalDoc).toMatch(/LightningK0ala\/jev-marshal/);
    expect(evalDoc).toMatch(/empty public tree at capture/i);
    expect(evalDoc).toMatch(/Victor-Casado\/if-ai/);
    expect(evalDoc).toMatch(/shitianfang\/wakegate/);
    expect(evalDoc).toMatch(/fail-open wake gate/);
    expect(evalDoc).toMatch(/alexsatch\/omp-auto-mode/);
    expect(evalDoc).toMatch(/fdemir\/toolgate/);
    expect(evalDoc).toMatch(/ndolinschi\/toolgate/);
    expect(evalDoc).toMatch(/`allow` \/ `block` \/ `review`/);
    expect(evalDoc).toMatch(/given → expected → actual/);
    expect(evalDoc).toMatch(/egma-ai\/jev-reviewer/);
    expect(evalDoc).toMatch(/attention priorities/);
    expect(evalDoc).toMatch(/blocked as unsafe/);
    expect(evalDoc).toMatch(/alwaysReviewPaths/);
    expect(evalDoc).toMatch(/EpicEric\/safe-sh/);
    expect(evalDoc).toMatch(/static shell/);
    expect(evalDoc).toMatch(/never executes/);
    expect(evalDoc).toMatch(/somoore\/interlock/);
    expect(evalDoc).toMatch(/secrets never enter the agent/);
    expect(evalDoc).toMatch(/38-case/);
    expect(evalDoc).toMatch(/not a blind paper/);
    expect(evalDoc).toMatch(/is this dangerous\?/);
    expect(evalDoc).toMatch(/epiphany-dynamics\/port-cleanup/);
    expect(evalDoc).toMatch(/identity re-check before SIGTERM/);
    expect(evalDoc).toMatch(/app-owned text/);
    expect(evalDoc).toMatch(/SECURITY_ESCALATE/);
    expect(evalDoc).toMatch(/manikanda-kumar\/jev-dspy-control-plane/);
    expect(evalDoc).toMatch(/meetr1912\/jev-arena/);
    expect(evalDoc).toMatch(/overconfident in the low bins/);
    expect(evalDoc).toMatch(/mja00\/cmdc-auto-mode/);
    expect(evalDoc).toMatch(/beforeToolCall/);
    expect(evalDoc).toMatch(/within_scope ≤ 0\.25/);
    expect(evalDoc).toMatch(/auto-fail-closed/);
    expect(evalDoc).toMatch(/Escalation always goes to a human/);
    expect(evalDoc).toMatch(/ragelink\/firehose-judge/);
    expect(evalDoc).toMatch(/needs a human/);
    expect(evalDoc).toMatch(/Durable Object/);
    expect(evalDoc).toMatch(/skiingfalcon\/jav-email-cascade/);
    expect(evalDoc).toMatch(/decide → policy → LLM leftover/);
    expect(evalDoc).toMatch(/injection_suspected/);
    expect(evalDoc).toMatch(/cannot tell/);
    expect(evalDoc).toMatch(/never rounded/);
    expect(evalDoc).toMatch(/mossburgh\/waymode/);
    expect(evalDoc).toMatch(/typed actions/);
    expect(evalDoc).toMatch(/retained evidence/);
    expect(evalDoc).toMatch(/Jev confidence grants no permission/);
    expect(evalDoc).toMatch(/adamjralph\/skill-broker/);
    expect(evalDoc).toMatch(/never grants access/);
    expect(evalDoc).toMatch(/luw2007\/omp-jev-extensions/);
    expect(evalDoc).toMatch(/jev_acceptance_gate/);
    expect(evalDoc).toMatch(/Fail-open, never fail-catch/);
    expect(evalDoc).toMatch(/SemetricLabs\/omp-greenlight/);
    expect(evalDoc).toMatch(/0\/94/);
    expect(evalDoc).toMatch(/never tunes its own threshold/);
    expect(evalDoc).toMatch(/[Gg]raded allow/);
    expect(evalDoc).toMatch(/Permission ≠ probability/);
    expect(evalDoc).toMatch(/ThyFriendlyFox\/jev-triage/);
    expect(evalDoc).toMatch(/teacher of record/);
    expect(evalDoc).toMatch(/mallahyari\/system-one-benchmark/);
    expect(evalDoc).toMatch(/90\.9%/);
    expect(evalDoc).toMatch(/uncalibrated open PCD/);
    expect(evalDoc).toMatch(/collapseindex\/dinostomp/);
    expect(evalDoc).toMatch(/mrmps\/classifier-dev/);
    expect(evalDoc).toMatch(/FALLBACK/);
    expect(evalDoc).toMatch(/0\.546/);
    expect(evalDoc).toMatch(/Undeclared fallback = eval integrity failure/);
    expect(evalDoc).toMatch(/Nothing in the deployed numbers said so/);
    expect(evalDoc).toMatch(/ibm-granite\/granite-4\.0-h-micro/);
    expect(evalDoc).toMatch(/check the instrument first/);
    expect(evalDoc).toMatch(/godspede\/construct-auto-classifier/);
    expect(evalDoc).toMatch(/0 dangerous/);
    expect(evalDoc).toMatch(/Privilege Is Not a Verdict/);
    expect(evalDoc).toMatch(/data_loss/);
    expect(evalDoc).toMatch(/minConfidence/);
    expect(evalDoc).toMatch(/riskThreshold/);
    expect(evalDoc).toMatch(/975/);
    expect(evalDoc).toMatch(/Hunch:/);
    expect(evalDoc).toMatch(/omkarghugarkar007\/actiongate-jev/);
    expect(evalDoc).toMatch(/Jev supplies evidence/);
    expect(evalDoc).toMatch(/Code owns authority/);
    expect(evalDoc).toMatch(/never overrides/);
    expect(evalDoc).toMatch(/Schema-valid ≠ intent-matched/);
    expect(evalDoc).toMatch(/single-use Action Grant/);
    expect(evalDoc).toMatch(/grants\/consume/);
    expect(evalDoc).toMatch(/reddpy\/AgentGhost/);
    expect(evalDoc).toMatch(/@agentghost\/sdk/);
    expect(evalDoc).toMatch(/tool's execution function/);
    expect(evalDoc).toMatch(/silently skipped/);
    expect(evalDoc).toMatch(/failMode/);
    expect(evalDoc).toMatch(/Nyarlathoteppppp\/pi-heed/);
    expect(evalDoc).toMatch(/instruction-drift/);
    expect(evalDoc).toMatch(/Jev never writes policy/);
    expect(evalDoc).toMatch(/Reindeer-AI\/pi-jev-guard/);
    expect(evalDoc).toMatch(/informative/);
    expect(evalDoc).toMatch(/violationThreshold/);
    expect(evalDoc).toMatch(/soundness theater/);
    expect(evalDoc).toMatch(/goodruizhan\/pi-jev-control/);
    expect(evalDoc).toMatch(/control plane/);
    expect(evalDoc).toMatch(/never force-click/);
    expect(evalDoc).toMatch(/shitianfang\/jev-use/);
    expect(evalDoc).toMatch(/jev_gate/);
    expect(evalDoc).toMatch(/only ever tightens/);
    expect(evalDoc).toMatch(/12\/12 correct/);
    expect(evalDoc).toMatch(/training claim/);
    expect(evalDoc).toMatch(/jimmyhealer\/jevex/);
    expect(evalDoc).toMatch(/what to read/);
    expect(evalDoc).toMatch(/kbhuw\/jev-sift/);
    expect(evalDoc).toMatch(/yodablocks\/commitjev/);
    expect(evalDoc).toMatch(/not a reason to refuse/);
    expect(evalDoc).toMatch(/IPECTER\/jev-runway/);
    expect(evalDoc).toMatch(/LICENSE only/);
    expect(evalDoc).toMatch(/dev-willbird1936\/pi-jev-compact/);
    expect(evalDoc).toMatch(/keepThreshold/);
    expect(evalDoc).toMatch(/robbyczgw-cla\/hermes-plugin-jev/);
    expect(evalDoc).toMatch(/cannot grant permission/);
    expect(evalDoc).toMatch(/nekowasabi\/jev-routing/);
    expect(evalDoc).toMatch(/1 schema/);
    expect(evalDoc).toMatch(/mrmps\/classifier-dev/);
    expect(evalDoc).toMatch(/advertised backend ≠ served backend/);
    expect(evalDoc).toMatch(/FALLBACK/);
    expect(evalDoc).toMatch(/0\.546/);
    expect(evalDoc).toMatch(/totally-tim\/jev-gate/);
    expect(evalDoc).toMatch(/soft-score-as-hard-rank/);
    expect(evalDoc).toMatch(/connectedGraph\/claude-jev-warden/);
    expect(evalDoc).toMatch(/warden-as-hard-gate/);
    expect(evalDoc).toMatch(/attention≠verdict/);
    expect(evalDoc).toMatch(/jonathanavis96\/jev-kit/);
    expect(evalDoc).toMatch(/This is not a security control/);
    expect(evalDoc).toMatch(/airlock-ok/);
    expect(evalDoc).toMatch(/agent-chaperone\/agent-chaperone/);
    expect(evalDoc).toMatch(/discarded without complaint/);
    expect(evalDoc).toMatch(/0\.976/);
    expect(evalDoc).toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(evalDoc).toMatch(/system directive, not a hard block/);
    expect(evalDoc).toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(evalDoc).toMatch(/tamaratran\/fast-jev-compaction/);
    expect(evalDoc).toMatch(/removedMessages/);
    expect(evalDoc).toMatch(/riz007\/yolo-shell/);
    expect(evalDoc).toMatch(/no silent fail-open when Jev is down/);
    expect(evalDoc).toMatch(/YOLO_BYPASS/);
    expect(evalDoc).toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(evalDoc).toMatch(/Command sent ≠ state confirmed/);
    expect(evalDoc).toMatch(/action ≠ verified outcome/);
    expect(evalDoc).toMatch(/muthuishere\/herdr-jev/);
    expect(evalDoc).toMatch(/Nothing here works yet/);
    expect(evalDoc).toMatch(/AlexWortega\/openjev/);
    expect(evalDoc).toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(evalDoc).toMatch(/advertised capability ≠ shipped module/);
    expect(evalDoc).toMatch(/shadow vs live/);
    expect(evalDoc).toMatch(/shadow_noop/);
    expect(evalDoc).toMatch(/alsoleg89\/jev-guard/);
    expect(evalDoc).toMatch(/Tripwires never deny/);
    expect(evalDoc).toMatch(/pablozr\/JevGuard/);
    expect(evalDoc).toMatch(/never turns incomplete evidence/);
    expect(evalDoc).toMatch(/advertised monorepo ≠ shipped packages/);
    expect(evalDoc).toMatch(/ybadragon\/jev-proving-ground/);
    expect(evalDoc).toMatch(/planted defect/);
    expect(evalDoc).toMatch(/verify-criteria/);
    expect(evalDoc).toMatch(/Synxneuos\/jevbrain/);
    expect(evalDoc).toMatch(/AUTO_ACT/);
    expect(evalDoc).toMatch(/REVIEW_QUEUE/);
    expect(evalDoc).toMatch(/russfranky\/jev-crawlers/);
    expect(evalDoc).toMatch(/unverified lead/);
    expect(evalDoc).toMatch(/ranking signals/);
    expect(evalDoc).toMatch(/githubnext\/localjev/);
    expect(evalDoc).toMatch(/consequential decisions/);
    expect(evalDoc).toMatch(/NandhaKishorM\/laya/);
    expect(evalDoc).toMatch(/95\.2%/);
    expect(evalDoc).toMatch(/ThyFriendlyFox\/jev-curate/);
    expect(evalDoc).toMatch(/curated\.jsonl/);
    expect(evalDoc).toMatch(/rejected\.jsonl/);
    expect(evalDoc).toMatch(/ohernandezdev\/jev-pr-review/);
    expect(evalDoc).toMatch(/Shadow-mode only/);
    expect(evalDoc).toMatch(/automerge path is unwritten/);
    expect(evalDoc).toMatch(/zyphr-labs\/turnstile/);
    expect(evalDoc).toMatch(/Jev never grants authority/);
    expect(evalDoc).toMatch(/copyleftdev\/jev-labs/);
    expect(evalDoc).toMatch(/Never confidently wrong/);
    expect(evalDoc).toMatch(/Reasonofmoon\/seal/);
    expect(evalDoc).toMatch(/coverage ledger/);
    expect(evalDoc).toMatch(/Hiding escalations is a product lie/);
    expect(evalDoc).toMatch(/schema-valid ≠ semantically correct/);
    expect(evalDoc).toMatch(/mint ≠ product brain/);
    expect(evalDoc).toMatch(/Adilmp\/jevcal/);
    expect(evalDoc).toMatch(/Ranking ≠ calibration/);
    expect(evalDoc).toMatch(/edwardyen724-g\/jev-compactor/);
    expect(evalDoc).toMatch(/regex floor/);
    expect(evalDoc).toMatch(/safetyGating/);
    expect(evalDoc).toMatch(/dtduc-git\/jev-packs/);
    expect(evalDoc).toMatch(/evidence-gated/);
    expect(evalDoc).toMatch(/NemanjaManic\/ci-gatekeeper-bot-jev/);
    expect(evalDoc).toMatch(/Vercel AI Gateway/);
    expect(evalDoc).toMatch(/should_review/);
    expect(evalDoc).toMatch(/touches_secrets/);
    expect(evalDoc).toMatch(/Zaious\/jev-capability-atlas/);
    expect(evalDoc).toMatch(/hold-vs-break/);
    expect(evalDoc).toMatch(/type-safe ≠ correct/);
    expect(evalDoc).toMatch(/scienthoon\/jev-ood-calibration/);
    expect(evalDoc).toMatch(/AUC ≠ ECE/);
    expect(evalDoc).toMatch(/noise floor/);
    expect(evalDoc).toMatch(/adarc8\/how-sure-is-jev/);
    expect(evalDoc).toMatch(/Adilmp\/does-jev-confidence-mean-anything/);
    expect(evalDoc).toMatch(/shubhangi013\/prune-review/);
    expect(evalDoc).toMatch(/safety escarpment/);
    expect(evalDoc).toMatch(/yottayoshida\/jev-intent-review/);
    expect(evalDoc).toMatch(/search hint/);
    expect(evalDoc).toMatch(/VERIFIED/);
    expect(evalDoc).toMatch(/VIOLATION/);
    expect(evalDoc).toMatch(/incomplete-change/);
    expect(evalDoc).toMatch(/zeeshan8281\/slo-router/);
    expect(evalDoc).toMatch(/77\.93/);
    expect(evalDoc).toMatch(/490\.38/);
    expect(evalDoc).toMatch(/exactness/);
    expect(evalDoc).toMatch(/rashedInt32\/jev-lens/);
    expect(evalDoc).toMatch(/never says green unless/);
    expect(evalDoc).toMatch(/JEV_LENS_GREEN/);
    expect(evalDoc).toMatch(/muse0509\/jev-preflight/);
    expect(evalDoc).toMatch(/eight risk axes/);
    expect(evalDoc).toMatch(/0\.85 threshold is uncalibrated/);
    expect(evalDoc).toMatch(/win4r\/jev-security-scan/);
    expect(evalDoc).toMatch(/Unflagged ≠ certified safe/);
    expect(evalDoc).toMatch(/bojansandhaus\/jev-decisions/);
    expect(evalDoc).toMatch(/JEV_ENABLE_HOOKS/);
    expect(evalDoc).toMatch(/failed review grants no permission/);
    expect(evalDoc).toMatch(/TeoMastro\/jev-vs-llm-guardrails-intent-router/);
    expect(evalDoc).toMatch(/96\.8%/);
    expect(evalDoc).toMatch(/classify accuracy is not a safety proof/);
    expect(evalDoc).toMatch(/ickma2311\/jev-baselines-eval/);
    expect(evalDoc).toMatch(/[Tt]hree same-day errata/);
    expect(evalDoc).toMatch(/AMBIGUOUS/);
    expect(evalDoc).toMatch(/Dharundp6\/jev-carryforward/);
    expect(evalDoc).toMatch(/nothing summarised/);
    expect(evalDoc).toMatch(/0\/4/);
    expect(evalDoc).toMatch(/hope the model looks/);
    expect(evalDoc).toMatch(/laurentfabre\/databricks-jev-pdf-lab/);
    expect(evalDoc).toMatch(/no quality-equivalent/);
    expect(evalDoc).toMatch(/suraj-phanindra\/wellposed/);
    expect(evalDoc).toMatch(/never the sole veto/);
    expect(evalDoc).toMatch(/Confidence gating cannot catch a forced wrong Choice/);
    expect(evalDoc).toMatch(/taskset \(score first\)/i);
    expect(evalDoc).toMatch(/independent validator/);
    expect(evalDoc).toMatch(/HoH evidence loop/);
    expect(evalDoc).toMatch(/do not replace a scored taskset/i);
    expect(evalDoc).toMatch(/never promote predictions to labels/i);
    expect(evalDoc).toMatch(/Correctness ≠ confidence/);
    expect(evalDoc).toMatch(/held-out discipline/i);
    expect(evalDoc).toMatch(/Compare only equivalent case sets/i);
    expect(evalDoc).toMatch(/LLM-as-judge/);
    expect(evalDoc).toMatch(/jevals measures decisions/);
    expect(evalDoc).toMatch(/rh-guard gates agent tool use/);
    expect(evalDoc).toMatch(/Harbor scores product\/agent loops/);
    expect(evalDoc).toMatch(/\*\*practices\*\*, not install dependencies/);
    expect(evalDoc).toMatch(/thevibeworks\/jevgate/);
    expect(evalDoc).toMatch(/huntedman\/JevLint/);
    expect(evalDoc).toMatch(/fastino-ai\/GLiGuard/);
    expect(evalDoc).toMatch(/coldteadotai\/abide/);
    expect(evalDoc).toMatch(/banded confidence/);
    expect(evalDoc).toMatch(/Harbor\/jevals-adjacent/);
    expect(evalDoc).toMatch(/not a claim that Abide measures reward hacking/);
    expect(install).toMatch(/RH Guard is \*\*not\*\*/);
    expect(install).toMatch(/RH_GUARD_URL/);
    expect(install).toMatch(/`HACK_RADAR_URL` is still accepted/);
    expect(install).toMatch(/practices, not install dependencies/);
    expect(install).toMatch(/coldteadotai\/abide/);
    expect(install).toMatch(/not a reward-hack detector/);
    expect(install).toMatch(/phin-tech\/pi-jev-approver/);
    expect(install).toMatch(/ngallodev-software\/agent-workflow-typesafe-ai/);
    expect(install).toMatch(/alexykn\/jevscan/);
    expect(install).toMatch(/ufx7\/jev-testbench/);
    expect(install).toMatch(/CeamKrier\/semantic-firewall/);
    expect(install).toMatch(/RahulBalakavi\/claude-code-jev/);
    expect(install).toMatch(/mjyoke1111\/jev-agent-safety-arena/);
    expect(install).toMatch(/Mandrilsquad1441\/jev-model-router/);
    expect(install).toMatch(/m-newhauser\/gliner25-compaction/);
    expect(install).toMatch(/CaseReed\/latch/);
    expect(install).toMatch(/VladyslavHontar\/clear-head/);
    expect(install).toMatch(/LightningK0ala\/jev-marshal/);
    expect(install).toMatch(/shitianfang\/wakegate/);
    expect(install).toMatch(/Victor-Casado\/if-ai/);
    expect(install).toMatch(/alexsatch\/omp-auto-mode/);
    expect(install).toMatch(/fdemir\/toolgate/);
    expect(install).toMatch(/egma-ai\/jev-reviewer/);
    expect(install).toMatch(/EpicEric\/safe-sh/);
    expect(install).toMatch(/somoore\/interlock/);
    expect(install).toMatch(/epiphany-dynamics\/port-cleanup/);
    expect(install).toMatch(/manikanda-kumar\/jev-dspy-control-plane/);
    expect(install).toMatch(/meetr1912\/jev-arena/);
    expect(install).toMatch(/mja00\/cmdc-auto-mode/);
    expect(install).toMatch(/ragelink\/firehose-judge/);
    expect(install).toMatch(/skiingfalcon\/jav-email-cascade/);
    expect(install).toMatch(/mossburgh\/waymode/);
    expect(install).toMatch(/SargeDev\/jev-gate-student-b/);
    expect(install).toMatch(/luw2007\/omp-jev-extensions/);
    expect(install).toMatch(/SemetricLabs\/omp-greenlight/);
    expect(install).toMatch(/adamjralph\/skill-broker/);
    expect(install).toMatch(/ThyFriendlyFox\/jev-triage/);
    expect(install).toMatch(/mallahyari\/system-one-benchmark/);
    expect(install).toMatch(/collapseindex\/dinostomp/);
    expect(install).toMatch(/mrmps\/classifier-dev/);
    expect(install).toMatch(/godspede\/construct-auto-classifier/);
    expect(install).toMatch(/omkarghugarkar007\/actiongate-jev/);
    expect(install).toMatch(/reddpy\/AgentGhost/);
    expect(install).toMatch(/Nyarlathoteppppp\/pi-heed/);
    expect(install).toMatch(/Reindeer-AI\/pi-jev-guard/);
    expect(install).toMatch(/goodruizhan\/pi-jev-control/);
    expect(install).toMatch(/shitianfang\/jev-use/);
    expect(install).toMatch(/jimmyhealer\/jevex/);
    expect(install).toMatch(/kbhuw\/jev-sift/);
    expect(install).toMatch(/yodablocks\/commitjev/);
    expect(install).toMatch(/IPECTER\/jev-runway/);
    expect(install).toMatch(/dev-willbird1936\/pi-jev-compact/);
    expect(install).toMatch(/robbyczgw-cla\/hermes-plugin-jev/);
    expect(install).toMatch(/nekowasabi\/jev-routing/);
    expect(install).toMatch(/mrmps\/classifier-dev/);
    expect(install).toMatch(/totally-tim\/jev-gate/);
    expect(install).toMatch(/connectedGraph\/claude-jev-warden/);
    expect(install).toMatch(/jonathanavis96\/jev-kit/);
    expect(install).toMatch(/agent-chaperone\/agent-chaperone/);
    expect(install).toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(install).toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(install).toMatch(/tamaratran\/fast-jev-compaction/);
    expect(install).toMatch(/riz007\/yolo-shell/);
    expect(install).toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(install).toMatch(/muthuishere\/herdr-jev/);
    expect(install).toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(install).toMatch(/alsoleg89\/jev-guard/);
    expect(install).toMatch(/pablozr\/JevGuard/);
    expect(install).toMatch(/ybadragon\/jev-proving-ground/);
    expect(install).toMatch(/Synxneuos\/jevbrain/);
    expect(install).toMatch(/russfranky\/jev-crawlers/);
    expect(install).toMatch(/githubnext\/localjev/);
    expect(install).toMatch(/NandhaKishorM\/laya/);
    expect(install).toMatch(/ThyFriendlyFox\/jev-curate/);
    expect(install).toMatch(/ohernandezdev\/jev-pr-review/);
    expect(install).toMatch(/zeeshan8281\/slo-router/);
    expect(install).toMatch(/rashedInt32\/jev-lens/);
    expect(install).toMatch(/edwardyen724-g\/jev-compactor/);
    expect(install).toMatch(/dtduc-git\/jev-packs/);
    expect(install).toMatch(/NemanjaManic\/ci-gatekeeper-bot-jev/);
    expect(install).toMatch(/zyphr-labs\/turnstile/);
    expect(install).toMatch(/copyleftdev\/jev-labs/);
    expect(install).toMatch(/Reasonofmoon\/seal/);
    expect(install).toMatch(/adarc8\/how-sure-is-jev/);
    expect(install).toMatch(/muse0509\/jev-preflight/);
    expect(install).toMatch(/win4r\/jev-security-scan/);
    expect(install).toMatch(/bojansandhaus\/jev-decisions/);
    expect(install).toMatch(/TeoMastro\/jev-vs-llm-guardrails-intent-router/);
    expect(install).toMatch(/Zaious\/jev-capability-atlas/);
    expect(install).toMatch(/scienthoon\/jev-ood-calibration/);
    expect(install).toMatch(/shubhangi013\/prune-review/);
    expect(install).toMatch(/yottayoshida\/jev-intent-review/);
    expect(install).toMatch(/ickma2311\/jev-baselines-eval/);
    expect(install).toMatch(/Dharundp6\/jev-carryforward/);
    expect(install).toMatch(/laurentfabre\/databricks-jev-pdf-lab/);
    expect(install).toMatch(/sibling notes; no runtime deps/);
    expect(install).toMatch(/examples\/pi-extension\.ts/);
    expect(shape).toMatch(/coldteadotai\/abide/);
    expect(shape).toMatch(/banded confidence/);
    expect(install).toMatch(/memovai\/openevals/);
    expect(install).toMatch(/eval-integrity\.md/);
    expect(shape).toMatch(/eval-integrity\.md/);
    expect(shape).toMatch(/LLM-as-judge/);
    expect(shape).toMatch(/memovai\/openevals/);
    expect(shape).toMatch(/suraj-phanindra\/wellposed/);
    expect(shape).toMatch(/alexsatch\/omp-auto-mode/);
    expect(shape).toMatch(/jonathanavis96\/jev-kit/);
    expect(shape).toMatch(/This is not a security control/);
    expect(shape).toMatch(/agent-chaperone\/agent-chaperone/);
    expect(shape).toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(shape).toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(shape).toMatch(/tamaratran\/fast-jev-compaction/);
    expect(shape).toMatch(/riz007\/yolo-shell/);
    expect(shape).toMatch(/no silent fail-open when Jev is down/);
    expect(shape).toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(shape).toMatch(/action ≠ verified outcome/);
    expect(shape).toMatch(/muthuishere\/herdr-jev/);
    expect(shape).toMatch(/Nothing here works yet/);
    expect(shape).toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(shape).toMatch(/advertised capability ≠ shipped module/);
    expect(shape).toMatch(/shadow vs live/);
    expect(shape).toMatch(/alsoleg89\/jev-guard/);
    expect(shape).toMatch(/Tripwires never deny/);
    expect(shape).toMatch(/pablozr\/JevGuard/);
    expect(shape).toMatch(/advertised monorepo ≠ shipped packages/);
    expect(shape).toMatch(/ybadragon\/jev-proving-ground/);
    expect(shape).toMatch(/Synxneuos\/jevbrain/);
    expect(shape).toMatch(/AUTO_ACT/);
    expect(shape).toMatch(/REVIEW_QUEUE/);
    expect(shape).toMatch(/russfranky\/jev-crawlers/);
    expect(shape).toMatch(/unverified lead/);
    expect(shape).toMatch(/ranking signals/);
  });

  it("keeps jevgate as a sibling link on host docs, not a merged product", () => {
    const hosts = readFileSync(join(root, "docs/hosts.md"), "utf8");
    expect(hosts).toMatch(/thevibeworks\/jevgate/);
    expect(hosts).toMatch(/allowlist proves what may run/i);
    expect(hosts).toMatch(/never the sole veto/);
    expect(hosts).toMatch(/Do not merge the products/i);
    expect(hosts).toMatch(/fastino-ai\/GLiGuard/);
    expect(hosts).toMatch(/coldteadotai\/abide/);
    expect(hosts).toMatch(/Abide does not catch\s+reward hacking/);
    expect(hosts).toMatch(/phin-tech\/pi-jev-approver/);
    expect(hosts).toMatch(/commandRules/);
    expect(hosts).toMatch(/alexsatch\/omp-auto-mode/);
    expect(hosts).toMatch(/fail-open/);
    expect(hosts).toMatch(/luw2007\/omp-jev-extensions/);
    expect(hosts).toMatch(/jev_acceptance_gate/);
    expect(hosts).toMatch(/never fail-catch/);
    expect(hosts).toMatch(/SemetricLabs\/omp-greenlight/);
    expect(hosts).toMatch(/0\/94/);
    expect(hosts).toMatch(/graded allow/);
    expect(hosts).toMatch(/RahulBalakavi\/claude-code-jev/);
    expect(hosts).toMatch(/fdemir\/toolgate/);
    expect(hosts).toMatch(/ndolinschi\/toolgate/);
    expect(hosts).toMatch(/fail-safe/);
    expect(hosts).toMatch(/egma-ai\/jev-reviewer/);
    expect(hosts).toMatch(/blocked as unsafe/);
    expect(hosts).toMatch(/EpicEric\/safe-sh/);
    expect(hosts).toMatch(/never executes/);
    expect(hosts).toMatch(/somoore\/interlock/);
    expect(hosts).toMatch(/secrets never enter the agent/);
    expect(hosts).toMatch(/interlock gate --claude-code/);
    expect(hosts).toMatch(/mja00\/cmdc-auto-mode/);
    expect(hosts).toMatch(/beforeToolCall/);
    expect(hosts).toMatch(/auto-fail-closed/);
    expect(hosts).toMatch(/within_scope ≤ 0\.25/);
    expect(hosts).toMatch(/godspede\/construct-auto-classifier/);
    expect(hosts).toMatch(/Privilege Is Not a Verdict/);
    expect(hosts).toMatch(/0 dangerous/);
    expect(hosts).toMatch(/omkarghugarkar007\/actiongate-jev/);
    expect(hosts).toMatch(/Jev supplies evidence/);
    expect(hosts).toMatch(/Code owns authority/);
    expect(hosts).toMatch(/never overrides/);
    expect(hosts).toMatch(/Schema-valid ≠ intent-matched/);
    expect(hosts).toMatch(/single-use Action Grant/);
    expect(hosts).toMatch(/wrapTool/);
    expect(hosts).toMatch(/reddpy\/AgentGhost/);
    expect(hosts).toMatch(/@agentghost\/sdk/);
    expect(hosts).toMatch(/tool's execution function/);
    expect(hosts).toMatch(/silently skipped/);
    expect(hosts).toMatch(/failMode/);
    expect(hosts).toMatch(/Nyarlathoteppppp\/pi-heed/);
    expect(hosts).toMatch(/instruction-drift/);
    expect(hosts).toMatch(/Reindeer-AI\/pi-jev-guard/);
    expect(hosts).toMatch(/goodruizhan\/pi-jev-control/);
    expect(hosts).toMatch(/never force-click/);
    expect(hosts).toMatch(/shitianfang\/jev-use/);
    expect(hosts).toMatch(/only ever tightens/);
    expect(hosts).toMatch(/jimmyhealer\/jevex/);
    expect(hosts).toMatch(/yodablocks\/commitjev/);
    expect(hosts).toMatch(/IPECTER\/jev-runway/);
    expect(hosts).toMatch(/dev-willbird1936\/pi-jev-compact/);
    expect(hosts).toMatch(/robbyczgw-cla\/hermes-plugin-jev/);
    expect(hosts).toMatch(/cannot grant permission/);
    expect(hosts).toMatch(/nekowasabi\/jev-routing/);
    expect(hosts).toMatch(/mrmps\/classifier-dev/);
    expect(hosts).toMatch(/advertised backend ≠ served backend/);
    expect(hosts).toMatch(/totally-tim\/jev-gate/);
    expect(hosts).toMatch(/soft-score-as-hard-rank/);
    expect(hosts).toMatch(/connectedGraph\/claude-jev-warden/);
    expect(hosts).toMatch(/warden-as-hard-gate/);
    expect(hosts).toMatch(/jonathanavis96\/jev-kit/);
    expect(hosts).toMatch(/This is not a security control/);
    expect(hosts).toMatch(/airlock-ok/);
    expect(hosts).toMatch(/agent-chaperone\/agent-chaperone/);
    expect(hosts).toMatch(/discarded without complaint/);
    expect(hosts).toMatch(/0\.976/);
    expect(hosts).toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(hosts).toMatch(/system directive, not a hard block/);
    expect(hosts).toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(hosts).toMatch(/tamaratran\/fast-jev-compaction/);
    expect(hosts).toMatch(/removedMessages/);
    expect(hosts).toMatch(/riz007\/yolo-shell/);
    expect(hosts).toMatch(/no silent fail-open when Jev is down/);
    expect(hosts).toMatch(/YOLO_BYPASS/);
    expect(hosts).toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(hosts).toMatch(/Command sent ≠ state confirmed/);
    expect(hosts).toMatch(/action ≠ verified outcome/);
    expect(hosts).toMatch(/muthuishere\/herdr-jev/);
    expect(hosts).toMatch(/Nothing here works yet/);
    expect(hosts).toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(hosts).toMatch(/advertised capability ≠ shipped module/);
    expect(hosts).toMatch(/shadow vs live/);
    expect(hosts).toMatch(/shadow_noop/);
    expect(hosts).toMatch(/alsoleg89\/jev-guard/);
    expect(hosts).toMatch(/Tripwires never deny/);
    expect(hosts).toMatch(/pablozr\/JevGuard/);
    expect(hosts).toMatch(/advertised monorepo ≠ shipped packages/);
    expect(hosts).toMatch(/ybadragon\/jev-proving-ground/);
    expect(hosts).toMatch(/planted defect/);
    expect(hosts).toMatch(/Synxneuos\/jevbrain/);
    expect(hosts).toMatch(/AUTO_ACT/);
    expect(hosts).toMatch(/REVIEW_QUEUE/);
    expect(hosts).toMatch(/russfranky\/jev-crawlers/);
    expect(hosts).toMatch(/unverified lead/);
    expect(hosts).toMatch(/ranking signals/);
    expect(hosts).toMatch(/githubnext\/localjev/);
    expect(hosts).toMatch(/consequential decisions/);
    expect(hosts).toMatch(/NandhaKishorM\/laya/);
    expect(hosts).toMatch(/95\.2%/);
    expect(hosts).toMatch(/ohernandezdev\/jev-pr-review/);
    expect(hosts).toMatch(/shadow-mode only until calibrated/);
    expect(hosts).toMatch(/yottayoshida\/jev-intent-review/);
    expect(hosts).toMatch(/VERIFIED/);
    expect(hosts).toMatch(/incomplete-change/);
    expect(hosts).toMatch(/zyphr-labs\/turnstile/);
    expect(hosts).toMatch(/Jev never grants authority/);
    expect(hosts).toMatch(/copyleftdev\/jev-labs/);
    expect(hosts).toMatch(/Never confidently wrong/);
    expect(hosts).toMatch(/Reasonofmoon\/seal/);
    expect(hosts).toMatch(/coverage ledger/);
    expect(hosts).toMatch(/Hiding escalations is a product lie/);
    expect(hosts).toMatch(/adarc8\/how-sure-is-jev/);
    expect(hosts).toMatch(/NemanjaManic\/ci-gatekeeper-bot-jev/);
    expect(hosts).toMatch(/should_review/);
    expect(hosts).toMatch(/touches_secrets/);
    expect(hosts).toMatch(/zeeshan8281\/slo-router/);
    expect(hosts).toMatch(/77\.93/);
    expect(hosts).toMatch(/exactness/);
    expect(hosts).toMatch(/rashedInt32\/jev-lens/);
    expect(hosts).toMatch(/never says green unless/);
    expect(hosts).toMatch(/muse0509\/jev-preflight/);
    expect(hosts).toMatch(/eight risk axes/);
    expect(hosts).toMatch(/0\.85 threshold is uncalibrated/);
    expect(hosts).toMatch(/win4r\/jev-security-scan/);
    expect(hosts).toMatch(/Unflagged ≠ certified safe/);
    expect(hosts).toMatch(/bojansandhaus\/jev-decisions/);
    expect(hosts).toMatch(/JEV_ENABLE_HOOKS/);
    expect(hosts).toMatch(/failed review grants no permission/);
    expect(hosts).toMatch(/TeoMastro\/jev-vs-llm-guardrails-intent-router/);
    expect(hosts).toMatch(/96\.8%/);
    expect(hosts).toMatch(/classify accuracy is not a safety proof/);
    expect(hosts).toMatch(/0\/4/);
    expect(hosts).toMatch(/hope the model looks/);
    expect(hosts).toMatch(/m-newhauser\/gliner25-compaction/);
    expect(hosts).toMatch(/character-offset/);
    expect(hosts).toMatch(/keep_full/);
    expect(hosts).toMatch(/shadowMode/);
    expect(hosts).toMatch(/hard shell\/mutation policy overrides the soft model/);
    expect(hosts).toMatch(/not reward-hack detection/);
    expect(hosts).toMatch(/230\.8ms p50/);
    expect(hosts).toMatch(/263\.9ms mean/);
    expect(hosts).toMatch(/hooks\/run\.ts dsh/);
    expect(hosts).toMatch(/command-hook/);
    const gates = readFileSync(
      join(root, ".agents/skills/rh-guard/references/gates.md"),
      "utf8"
    );
    expect(gates).toMatch(/coldteadotai\/abide/);
    expect(gates).toMatch(/never the sole hard veto/);
    expect(gates).toMatch(/phin-tech\/pi-jev-approver/);
    expect(gates).toMatch(/commandRules/);
    expect(gates).toMatch(/alexykn\/jevscan/);
    expect(gates).toMatch(/tree-sitter extract/);
    expect(gates).toMatch(/ngallodev-software\/agent-workflow-typesafe-ai/);
    expect(gates).toMatch(/never changes host routing\/executor/);
    expect(gates).toMatch(/hard envelope stays structural/);
    expect(gates).toMatch(/CeamKrier\/semantic-firewall/);
    expect(gates).toMatch(/skip-when-absent/);
    expect(gates).toMatch(/RahulBalakavi\/claude-code-jev/);
    expect(gates).toMatch(/typesafe\/jev-1\.13/);
    expect(gates).toMatch(/Mandrilsquad1441\/jev-model-router/);
    expect(gates).toMatch(/not a rh-guard peer/);
    expect(gates).toMatch(/m-newhauser\/gliner25-compaction/);
    expect(gates).toMatch(/character-offset/);
    expect(gates).toMatch(/keep_full/);
    expect(gates).toMatch(/shadowMode/);
    expect(gates).toMatch(/hard shell\/mutation policy overrides the soft model/);
    expect(gates).toMatch(/not reward-hack detection/);
    expect(gates).toMatch(/CaseReed\/latch/);
    expect(gates).toMatch(/Gate: PASS/);
    expect(gates).toMatch(/ignore_as_infra/);
    expect(gates).toMatch(/VladyslavHontar\/clear-head/);
    expect(gates).toMatch(/CONTRADICTED/);
    expect(gates).toMatch(/shitianfang\/wakegate/);
    expect(gates).toMatch(/fail-open wake/);
    expect(gates).toMatch(/alexsatch\/omp-auto-mode/);
    expect(gates).toMatch(/luw2007\/omp-jev-extensions/);
    expect(gates).toMatch(/jev_acceptance_gate/);
    expect(gates).toMatch(/never fail-catch/);
    expect(gates).toMatch(/SemetricLabs\/omp-greenlight/);
    expect(gates).toMatch(/0\/94/);
    expect(gates).toMatch(/never tunes its own threshold/);
    expect(gates).toMatch(/godspede\/construct-auto-classifier/);
    expect(gates).toMatch(/Privilege Is Not a Verdict/);
    expect(gates).toMatch(/0 dangerous/);
    expect(gates).toMatch(/data_loss/);
    expect(gates).toMatch(/minConfidence/);
    expect(gates).toMatch(/omkarghugarkar007\/actiongate-jev/);
    expect(gates).toMatch(/Jev supplies evidence/);
    expect(gates).toMatch(/Code owns authority/);
    expect(gates).toMatch(/never overrides/);
    expect(gates).toMatch(/Schema-valid ≠ intent-matched/);
    expect(gates).toMatch(/single-use Action Grant/);
    expect(gates).toMatch(/reddpy\/AgentGhost/);
    expect(gates).toMatch(/@agentghost\/sdk/);
    expect(gates).toMatch(/tool's execution function/);
    expect(gates).toMatch(/silently skipped/);
    expect(gates).toMatch(/failMode/);
    expect(gates).toMatch(/Nyarlathoteppppp\/pi-heed/);
    expect(gates).toMatch(/instruction-drift/);
    expect(gates).toMatch(/Reindeer-AI\/pi-jev-guard/);
    expect(gates).toMatch(/violationThreshold/);
    expect(gates).toMatch(/goodruizhan\/pi-jev-control/);
    expect(gates).toMatch(/never force-click/);
    expect(gates).toMatch(/shitianfang\/jev-use/);
    expect(gates).toMatch(/only ever tightens/);
    expect(gates).toMatch(/jimmyhealer\/jevex/);
    expect(gates).toMatch(/what to read/);
    expect(gates).toMatch(/yodablocks\/commitjev/);
    expect(gates).toMatch(/not a reason to refuse/);
    expect(gates).toMatch(/IPECTER\/jev-runway/);
    expect(gates).toMatch(/LICENSE-only/);
    expect(gates).toMatch(/dev-willbird1936\/pi-jev-compact/);
    expect(gates).toMatch(/keepThreshold/);
    expect(gates).toMatch(/robbyczgw-cla\/hermes-plugin-jev/);
    expect(gates).toMatch(/cannot grant permission/);
    expect(gates).toMatch(/nekowasabi\/jev-routing/);
    expect(gates).toMatch(/1 schema/);
    expect(gates).toMatch(/mrmps\/classifier-dev/);
    expect(gates).toMatch(/advertised backend ≠ served backend/);
    expect(gates).toMatch(/FALLBACK/);
    expect(gates).toMatch(/0\.546/);
    expect(gates).toMatch(/totally-tim\/jev-gate/);
    expect(gates).toMatch(/soft-score-as-hard-rank/);
    expect(gates).toMatch(/connectedGraph\/claude-jev-warden/);
    expect(gates).toMatch(/warden-as-hard-gate/);
    expect(gates).toMatch(/attention≠verdict/);
    expect(gates).toMatch(/jonathanavis96\/jev-kit/);
    expect(gates).toMatch(/This is not a security control/);
    expect(gates).toMatch(/airlock-ok/);
    expect(gates).toMatch(/agent-chaperone\/agent-chaperone/);
    expect(gates).toMatch(/discarded without complaint/);
    expect(gates).toMatch(/0\.976/);
    expect(gates).toMatch(/hoshinodis\/opencode-intent-gate/);
    expect(gates).toMatch(/system directive, not a hard block/);
    expect(gates).toMatch(/hoshinodis\/opencode-context-pruner/);
    expect(gates).toMatch(/tamaratran\/fast-jev-compaction/);
    expect(gates).toMatch(/removedMessages/);
    expect(gates).toMatch(/riz007\/yolo-shell/);
    expect(gates).toMatch(/no silent fail-open when Jev is down/);
    expect(gates).toMatch(/YOLO_BYPASS/);
    expect(gates).toMatch(/bojansandhaus\/jev-home-assistant-sentinel/);
    expect(gates).toMatch(/Command sent ≠ state confirmed/);
    expect(gates).toMatch(/action ≠ verified outcome/);
    expect(gates).toMatch(/muthuishere\/herdr-jev/);
    expect(gates).toMatch(/Nothing here works yet/);
    expect(gates).toMatch(/AiPersonacademy\/apa-agent-harness/);
    expect(gates).toMatch(/advertised capability ≠ shipped module/);
    expect(gates).toMatch(/shadow vs live/);
    expect(gates).toMatch(/shadow_noop/);
    expect(gates).toMatch(/alsoleg89\/jev-guard/);
    expect(gates).toMatch(/Tripwires never deny/);
    expect(gates).toMatch(/pablozr\/JevGuard/);
    expect(gates).toMatch(/advertised monorepo ≠ shipped packages/);
    expect(gates).toMatch(/ybadragon\/jev-proving-ground/);
    expect(gates).toMatch(/planted defect/);
    expect(gates).toMatch(/verify-criteria/);
    expect(gates).toMatch(/Synxneuos\/jevbrain/);
    expect(gates).toMatch(/AUTO_ACT/);
    expect(gates).toMatch(/REVIEW_QUEUE/);
    expect(gates).toMatch(/russfranky\/jev-crawlers/);
    expect(gates).toMatch(/unverified lead/);
    expect(gates).toMatch(/ranking signals/);
    expect(gates).toMatch(/githubnext\/localjev/);
    expect(gates).toMatch(/consequential decisions/);
    expect(gates).toMatch(/NandhaKishorM\/laya/);
    expect(gates).toMatch(/95\.2%/);
    expect(gates).toMatch(/ThyFriendlyFox\/jev-curate/);
    expect(gates).toMatch(/curated\.jsonl/);
    expect(gates).toMatch(/ohernandezdev\/jev-pr-review/);
    expect(gates).toMatch(/shadow-mode only until calibrated/);
    expect(gates).toMatch(/zyphr-labs\/turnstile/);
    expect(gates).toMatch(/Jev never grants authority/);
    expect(gates).toMatch(/copyleftdev\/jev-labs/);
    expect(gates).toMatch(/Never confidently wrong/);
    expect(gates).toMatch(/Reasonofmoon\/seal/);
    expect(gates).toMatch(/coverage ledger/);
    expect(gates).toMatch(/Hiding escalations is a product lie/);
    expect(gates).toMatch(/schema-valid ≠ semantically correct/);
    expect(gates).toMatch(/mint ≠ product brain/);
    expect(gates).toMatch(/Zaious\/jev-capability-atlas/);
    expect(gates).toMatch(/hold-vs-break/);
    expect(gates).toMatch(/type-safe ≠ correct/);
    expect(gates).toMatch(/scienthoon\/jev-ood-calibration/);
    expect(gates).toMatch(/AUC ≠ ECE/);
    expect(gates).toMatch(/noise floor/);
    expect(gates).toMatch(/adarc8\/how-sure-is-jev/);
    expect(gates).toMatch(/edwardyen724-g\/jev-compactor/);
    expect(gates).toMatch(/regex floor/);
    expect(gates).toMatch(/dtduc-git\/jev-packs/);
    expect(gates).toMatch(/evidence-gated/);
    expect(gates).toMatch(/NemanjaManic\/ci-gatekeeper-bot-jev/);
    expect(gates).toMatch(/Vercel AI Gateway/);
    expect(gates).toMatch(/should_review/);
    expect(gates).toMatch(/touches_secrets/);
    expect(gates).toMatch(/shubhangi013\/prune-review/);
    expect(gates).toMatch(/safety escarpment/);
    expect(gates).toMatch(/yottayoshida\/jev-intent-review/);
    expect(gates).toMatch(/search hint/);
    expect(gates).toMatch(/VERIFIED/);
    expect(gates).toMatch(/VIOLATION/);
    expect(gates).toMatch(/incomplete-change/);
    expect(gates).toMatch(/zeeshan8281\/slo-router/);
    expect(gates).toMatch(/77\.93/);
    expect(gates).toMatch(/490\.38/);
    expect(gates).toMatch(/exactness/);
    expect(gates).toMatch(/mrmps\/classifier-dev/);
    expect(gates).toMatch(/FALLBACK/);
    expect(gates).toMatch(/0\.546/);
    expect(gates).toMatch(/undeclared fallback = eval integrity failure/);
    expect(gates).toMatch(/adamjralph\/skill-broker/);
    expect(gates).toMatch(/never grants access/);
    expect(gates).toMatch(/rashedInt32\/jev-lens/);
    expect(gates).toMatch(/never says green unless/);
    expect(gates).toMatch(/muse0509\/jev-preflight/);
    expect(gates).toMatch(/eight risk axes/);
    expect(gates).toMatch(/0\.85 threshold is uncalibrated/);
    expect(gates).toMatch(/win4r\/jev-security-scan/);
    expect(gates).toMatch(/Unflagged ≠ certified safe/);
    expect(gates).toMatch(/bojansandhaus\/jev-decisions/);
    expect(gates).toMatch(/JEV_ENABLE_HOOKS/);
    expect(gates).toMatch(/failed review grants no permission/);
    expect(gates).toMatch(/TeoMastro\/jev-vs-llm-guardrails-intent-router/);
    expect(gates).toMatch(/96\.8%/);
    expect(gates).toMatch(/classify accuracy is not a safety proof/);
    expect(gates).toMatch(/fdemir\/toolgate/);
    expect(gates).toMatch(/ndolinschi\/toolgate/);
    expect(gates).toMatch(/given → expected → actual/);
    expect(gates).toMatch(/fail-safe/);
    expect(gates).toMatch(/egma-ai\/jev-reviewer/);
    expect(gates).toMatch(/blocked as unsafe/);
    expect(gates).toMatch(/EpicEric\/safe-sh/);
    expect(gates).toMatch(/never executes/);
    expect(gates).toMatch(/somoore\/interlock/);
    expect(gates).toMatch(/secrets never enter the agent/);
    expect(gates).toMatch(/epiphany-dynamics\/port-cleanup/);
    expect(gates).toMatch(/identity re-check before SIGTERM/);
    expect(gates).toMatch(/manikanda-kumar\/jev-dspy-control-plane/);
    expect(gates).toMatch(/cannot add routes\/tools/);
    expect(gates).toMatch(/mja00\/cmdc-auto-mode/);
    expect(gates).toMatch(/beforeToolCall/);
    expect(gates).toMatch(/auto-fail-closed/);
    expect(gates).toMatch(/ragelink\/firehose-judge/);
    expect(gates).toMatch(/needs a human/);
    expect(gates).toMatch(/skiingfalcon\/jav-email-cascade/);
    expect(gates).toMatch(/decide → policy → LLM leftover/);
    expect(gates).toMatch(/injection_suspected/);
    expect(gates).toMatch(/cannot tell/);
    expect(gates).toMatch(/never rounded/);
    expect(gates).toMatch(/mossburgh\/waymode/);
    expect(gates).toMatch(/typed actions/);
    expect(gates).toMatch(/retained evidence/);
    expect(gates).toMatch(/Jev confidence grants no permission/);
    expect(gates).toMatch(/Dharundp6\/jev-carryforward/);
    expect(gates).toMatch(/nothing summarised/);
    expect(gates).toMatch(/0\/4/);
    expect(gates).toMatch(/hope the model looks/);
  });
});

describe("multi-host examples/", () => {
  it("keeps Codex command-only and Codex-safe", () => {
    const pre = codexHooks.hooks.PreToolUse[0];
    expect(commandOf(pre)).toBe("npx tsx hooks/run.ts codex");
    expect(pre.hooks.every((hook) => hook.type === "command")).toBe(true);
    expect(JSON.stringify(codexHooks)).not.toMatch(/"type": "http"/);
    expect(JSON.stringify(codexHooks)).not.toMatch(/continue/);
  });

  it("points Grok at run.ts grok and ships a Grok deny wrapper", () => {
    expect(commandOf(grokHooks.hooks.PreToolUse[0])).toBe(
      "npx tsx hooks/run.ts grok"
    );
    const script = readFileSync(join(root, "hooks/grok-hook.sh"), "utf8");
    expect(script).toContain(AGENT_DENY);
    expect(script).toContain('"decision":"deny"');
    expect(script).not.toContain("hookSpecificOutput");
    expect(script).toContain("/api/hooks/grok");
  });

  it("keeps Pi command settings command-only for @hsingjui/pi-hooks", () => {
    const pre = piHooksSettings.hooks.PreToolUse[0];
    expect(commandOf(pre)).toBe("npx tsx hooks/run.ts claude");
    expect(pre.matcher).toBe("bash|edit|write");
    expect(pre.hooks.every((hook) => hook.type === "command")).toBe(true);
    expect(JSON.stringify(piHooksSettings)).not.toMatch(/"type": "http"/);
  });

  it("ships self-contained Pi/Amp/Prime copies with opaque AGENT_DENY", () => {
    const pi = readFileSync(join(root, "examples/pi-extension.ts"), "utf8");
    const amp = readFileSync(join(root, "examples/amp-plugin.ts"), "utf8");
    const prime = readFileSync(join(root, "examples/prime-extension.ts"), "utf8");
    for (const src of [pi, amp, prime]) {
      expect(src).toContain(AGENT_DENY);
      expect(src).toMatch(/fetch\(/);
      expect(src).not.toMatch(/@ampcode\/plugin/);
      expect(src).not.toMatch(/@earendil-works\/pi-coding-agent/);
    }
    expect(pi).toMatch(/terminate:\s*true/);
    expect(pi).toContain("/api/hooks/pi");
    expect(prime).not.toMatch(/terminate\s*:/);
    expect(prime).toContain("/api/hooks/prime");
    expect(amp).toMatch(/reject-and-continue/);
    expect(amp).not.toMatch(/action:\s*"error"/);
    expect(amp).toContain("/api/hooks/amp");
  });

  it("documents Exo as ToolRuntime wrap, not drop-in hooks", () => {
    const ts = readFileSync(join(root, "examples/exo-tool-runtime.ts"), "utf8");
    const rs = readFileSync(join(root, "examples/exo-tool-runtime.rs"), "utf8");
    const hosts = readFileSync(join(root, "docs/hosts.md"), "utf8");
    for (const src of [ts, rs, hosts]) {
      expect(src).toContain(AGENT_DENY);
      expect(src).toMatch(/ToolRuntime/);
    }
    expect(ts).toMatch(/executeTool/);
    expect(hosts).toMatch(/not drop-in hooks/i);
    expect(hosts).toMatch(/DeepSeek Harness/);
  });

  it("uses a Next 16 Promise params dynamic hook route", () => {
    const route = readFileSync(
      join(root, "src/app/api/hooks/[flavor]/route.ts"),
      "utf8"
    );
    expect(route).toMatch(/params: Promise<\{ flavor: string \}>/);
    expect(route).toMatch(/toHostOutput/);
    expect(route).toMatch(/httpEnabled/);
    expect(route).toMatch(/has no HTTP hook type/);
  });
});

describe("fail-closed Claude adapter", () => {
  it("embeds the same opaque deny as failClosedClaudeOutput()", () => {
    const script = readFileSync(join(root, "hooks/claude-hook.sh"), "utf8");
    const out = failClosedClaudeOutput("PreToolUse");
    expect(script).toContain(AGENT_DENY);
    expect(script).toContain(out.reason);
    expect(script).toContain('"permissionDecision":"deny"');
    expect(out.hookSpecificOutput?.permissionDecisionReason).toBe(AGENT_DENY);
  });
});
